### ISSUE TITLE
Window/monitor issues + crash

### ISSUE THREAD

**Issue by ghuser404** [glfw/glfw#1106] opened 2017-10-26 03:35 UTC
> If a monitor is disconnected, any windows that are full screen on it get forced into windowed mode.

> If a monitor is disconnected, any window that is full screen on that monitor will be forced into windowed mode.

1. Wording is a bit different between two files.
2. I didn't find the `any window that is full screen on that monitor will be forced into windowed mode` bit to be true, at least on Windows. This actually depended on resolution that I was initially setting, a very small resolution resulted in window being forced into windowed mode, after monitor was disconnected.
3. When I call `glfwSetWindowMonitor` for a monitor, other than primary, specifying video mode lower than native (resolution or refresh rate), my mouse cursor is centred on my primary monitor - which in turn causes task bar to pop up on the specified monitor. Cursor is also centred on primary monitor when window is restored by clicking on icon after being minimized. Task bar may not always pop up, I found there is more chance for it to pop up after being restored after being minimized, but in the end it depended on how low video mode I was setting.
4. When I disconnect a monitor that has a fullscreen window on it, the window moves to the other monitor (still being fullscreen) - now, when I minimize it and then restore it by clicking on the icon, I get a crash in `compareVideoModes` function. I first thought that the window manager wasn't doing its part, because I wouldn't get any crash, but the window just wasn't restoring. But turned out that this was the case because I was running debug build without debugging. Now that I ran debug build with debugging, I see that there is a crash.

**Comment by elmindreda** [comment] 2017-10-26 15:50
I haven't been able to reproduce all of this yet, but enough of it to tag it __verified__.

**Comment by elmindreda** [comment] 2017-10-26 16:45
> I didn't find the _any window that is full screen on that monitor will be forced into windowed mode_ bit to be true, at least on Windows.

So... the reason this doesn't work is that I forgot to bring it over when restructuring the internal monitor logic. 🦉

**Comment by ghuser404** [comment] 2017-10-26 16:51
Right. This might also fix the crash I described in 4.

**Comment by elmindreda** [comment] 2017-10-26 17:01
See if the `get-content-scale` branch works for you. Planning to merge it later today so I'm doing all other monitor-related work on it.

**Comment by ghuser404** [comment] 2017-10-26 17:11
@elmindreda, sure, I'll give it a go right now!

**Comment by ghuser404** [comment] 2017-10-26 17:57
@elmindreda, just tried it and here are my comments:

1. The window is now always forced into windowed mode, as per the documentation.
2. The crash is gone.
3. However, I noticed that the code just puts the window at 0, 0 position with its current size. While this will be OK for most people, it may not be for others: it doesn't take decorations into consideration. I think it could take the decorations offset and put the window at 0, 0 + offset with the current size minus decorations size.
4. Mouse cursor still jumps to the centre of my primary monitor, as per the comments in my original post.
5. Task bar still pops up, as per the comments in my original post.

- What is your opinion on 3?
- Were you able to reproduce 4 and 5?

**Comment by ghuser404** [comment] 2017-10-26 18:02
Just a follow-up to my previous comment section 3: why decorations matter is because the final window will be cropped if both of your monitors have the same resolution - window manager on Windows will limit the size of your window + decorations to fullscreen.

**Comment by ghuser404** [comment] 2017-10-27 17:08
I just found that cursor jumping to the primary monitor is the default behaviour on Windows 👀 
Looking forward to #58

**Comment by elmindreda** [comment] 2017-11-01 20:40
> Wording is a bit different between two files.

Fixed with 9718675d86fe2013c7b5965ff394391f24df02ba.

> I noticed that the code just puts the window at 0, 0 position with its current size. While this will be OK for most people, it may not be for others: it doesn't take decorations into consideration. I think it could take the decorations offset and put the window at 0, 0 + offset with the current size minus decorations size.

That would be an improvement but still wouldn't be enough for sane placement. We'll need #920 to do this properly. Still, it may be worth doing what we can for now.

> Task bar still pops up, as per the comments in my original post.
> Task bar may not always pop up, I found there is more chance for it to pop up after being restored after being minimized, but in the end it depended on how low video mode I was setting.

I'm not sure what this refers to.

**Comment by ghuser404** [comment] 2017-11-01 22:17
> I'm not sure what "task bar pops up" means.

Means - appears on top of fullscreen window.

**Comment by elmindreda** [comment] 2017-11-15 14:41
With 7b877c4e2450aeba17c0ef3ed9134f69561f8b5c I believe we've come as far as we're going to get with this in 3.3.

**Comment by elmindreda** [comment] 2017-11-15 14:41
Thank you so much for this and all your other detailed bug reports!

**Closed** 2017-11-15 18:48 UTC
Labels: bug, verified, Windows

**Comment by elmindreda** [comment] 2019-04-25 17:17
Oh, hey, we have work areas now. Will have another look at this.
