### ISSUE TITLE
Failed to initialize GLFW: failed to watch joystick

### ISSUE THREAD

**Issue by thacoon** [glfw/glfw#833] opened 2016-08-13 10:22 UTC
Hi,
I have installed glfw and I get the following error:
`Linux: Failed to watch for joystick connections in /dev/input: No space left on device`

`glfwInit()` fails to initialize without joystick support.

I am using Arch Linux (linux 4.7-1) and I have installed glfw-x11 (3.2-4) via pacman. I have also tried to solve this problem by compiling the stable version 3.2.

I can run it without error when running as sudo.

This is the code I am running:

``` c
#include <stdio.h>
#include <stdlib.h>
#include <GL/glew.h>
#include <GLFW/glfw3.h> //on Arch: glfw-x11
#include <glm/glm.hpp>

void error_callback(int error, const char* description)
{
    puts(description);
}

int main(int argc, char *argv[])
{
    glfwSetErrorCallback(error_callback);

    // Initialise GLFW
    if( !glfwInit() )
    {
        fprintf( stderr, "Failed to initialize GLFW\n" );
        return -1;
    }

    return 0;
}
```

I have just found one similar issue, but for [go-gl](https://github.com/go-gl): [Can not initialize GLFW without joystick support](https://github.com/go-gl/glfw/issues/127)

**Comment by CaffeineViking** [comment] 2016-08-13 11:36
Seems the error originates from [glfwInitJoysticksLinux](https://github.com/glfw/glfw/blob/master/src/linux_joystick.c#L193-L203), whenever `inotify_add_watch` fails with `-1` flag. I'm not experiencing these issues myself, and I'm sitting on the exact same setup as you @thacoon. So, according to the manual/posts referenced below, it seems `ENOSPC` (The user limit on the total number of inotify watches was reached or the kernel failed to allocate a needed resource) was triggered. Which has primarily been caused when `fs.inotify.max_user_watches` is exceeded. My system reports `8192` upon `cat /proc/sys/fs/inotify/max_user_watches` is executed. @thacoon, would you mind also trying this? Might be a good idea to look at the output of `tail -f | dmesg` for any additional reports by the system.

Also, please attempt increasing `fs.inotify.max_user_watches` temporarily by issuing a higher value for it e.g. `echo 16384 > /proc/sys/fs/inotify/max_user_watches` (won't be permanent, so no worries :wink:). Then attempt initializing glfw again, and report your results. This isn't a fix, but it might help debugging it.

* **inotify:** http://linux.die.net/man/7/inotify
* **limit of inotify:** http://blog.sorah.jp/2012/01/24/inotify-limitation
* **inotify_add_watch:** http://linux.die.net/man/2/inotify_add_watch
* http://askubuntu.com/questions/154255/how-can-i-tell-if-i-am-out-of-inotify-watches

**Comment by thacoon** [comment] 2016-08-13 11:51
Yep, increasing `fs.inotify.max_user_watches` fixed the issue. Thanks :smile: 

With ` cat /proc/sys/fs/inotify/max_user_watches` I also get `8192`.

The [Atom Editor](https://github.com/atom/atom) also complained about `fs.inotify.max_user_watches` and I get rid of the error by using there [Troubleshooting](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#typeerror-unable-to-watch-path):
I tried it temporarly with:
`sudo sysctl fs.inotify.max_user_watches=32768`
it worked and now I have made it permanent with:
`echo 32768 | sudo tee -a /proc/sys/fs/inotify/max_user_watches`

**Comment by CaffeineViking** [comment] 2016-08-13 17:16
@thacoon try setting `fs.inotify.max_user_watches=32768` in `/etc/sysctl.d/99-sysctl.conf`, should work for applying it permanently. Reload kernel parameters with `sysctl --system`. From the [Arch Wiki](https://wiki.archlinux.org/index.php/dropbox#Filesystem_monitoring_problem).

**Comment by elmindreda** [comment] 2016-08-14 19:57
> `glfwInit` fails to initialize without joystick support.

This is a bug. The function should still succeed even if joystick support is unavailable.

**Comment by CaffeineViking** [comment] 2016-08-15 08:44
Aha, sorry @elmindreda for jumping to conclusions. So the failure state in [x11_init](https://github.com/glfw/glfw/blob/master/src/x11_init.c#L768-L769) shouldn't happen because there isn't any joystick support for notifying the connection? Looking over the [linux_joystick](https://github.com/glfw/glfw/blob/master/src/linux_joystick.c#L196-L203), seems to imply it's trying to do things correctly `Continue without device connection notifications` not returning `GLFW_FALSE`. Therefore it must be something after `inotify_add_watch` that returns an failure state regardless, even though it should proceed silently (just reporting said error messages)? Again, sorry for jumping into conclusions, :see_no_evil:. Might be we still need your help soon, @thacoon, for debugging this. I'm currently having problems in reproducing these issues on my own machine.

**Comment by thacoon** [comment] 2016-08-15 08:48
@CaffeineViking can I share any information from my machine that may help you?

**Comment by elmindreda** [comment] 2016-08-15 17:28
@CaffeineViking There's nothing to apologize for. Your diagnosis is correct, and very detailed too, it's just that it shouldn't cause `glfwInit` to fail.

**Comment by elmindreda** [comment] 2016-08-15 17:30
@thacoon Just to verify, `glfwInit` does indeed return `GLFW_FALSE` on your machine?

**Comment by thacoon** [comment] 2016-08-16 13:37
@elmindreda Yes `glfwInit` returned `GLFW_FALSE`, the if statement was called every time until I have increased `fs.inotify.max_user_watches`

**Comment by CaffeineViking** [comment] 2016-08-17 12:34
Thanks for offering your help @thacoon! Since I can't reproduce these issues, you are going to have to feed us some debugging information, more specifically, we want to find out exactly where the `glfwInit` function returns with `GLFW_FALSE`, that should give us enough information to start working with. Alright, so the first step is *building* `glfw` with *debugging information*. The snipplet below, should (hopefully), do this for you by *cloning* and then *compiling* with certain flags that then enable `gdb` to reason about this.

```bash
git clone https://github.com/glfw/glfw.git
cd glfw ; mkdir build ; cd build
cmake -DCMAKE_BUILD_TYPE=Debug ..
make -j8

```
Additionally, when you have executed the commands above, this should have created a `glfw` directory, and created and moved you to an internal `build` directory, then finally building. Please stay in `build`, we are going to start gathering some information now. Below follow a series of commands that will open `tests/glfwinfo` and start *logging* its execution flow to a `gdb.txt` file in the `build` directory (a current one). Basically, we halt execution when we reach `glfwInit`, then proceed to step over statements with the `next` command (printing these to the log) until we have returned from the `glfwInit` function (base pointer hack). Finally, we just exit. Two files should now exist: `gdb.txt` and `.gdb_history`. If you could be so kind to copy the contents of these files here, that would help quite a lot in debugging this issue! :+1:

```bash
gdb tests/glfwinfo
set history save on
set logging overwrite on
set logging on
break glfwInit
run
set $glfwInitBase = $rbp
while $rbp == $glfwInitBase
  next
end
set logging off
continue
quit

```

If something goes wrong or doesn't work correctly, connect to [GLFW IRC](http://webchat.freenode.net/?randomnick=1&channels=%23glfw) and I'll try to help you with this.

**Comment by thacoon** [comment] 2016-08-18 07:44
@CaffeineViking I am currently not at home, it may take a few days before I can answer again. I'll do it as soon as I am back home.

**Comment by thacoon** [comment] 2016-08-18 09:42
Ok, I did another run now, should be correct now:
[gdb_history.txt](https://github.com/glfw/glfw/files/424521/gdb_history.txt)
[gdb.txt](https://github.com/glfw/glfw/files/424522/gdb.txt)

`openJoystickDevice` returns `GLFW_FALSE`. 

In the gdb.txt file `GLFW_FALSE` is only mentioned twice. The other one can be found in `_glfwPlatformInit` where `GLFWbool found = GLFW_FALSE; `, but I checked it with gdb and ` found` is assigned to 1 (`GLFW_TRUE`) and the function returns with `GLFW_TRUE`.

**Comment by CaffeineViking** [comment] 2016-08-19 09:07
Thanks for the information @thacoon! Based on the output of `gdb.txt`, it seems that `glfwInit` returns `GLFW_TRUE`, which is the correct behaviour. (even though the `inotify_add_watch` call fails with `-1`), :+1:, just as you mentioned in the post above too, meaning `_glfwInitJoysticksLinux` did return `GLFW_TRUE`. The reason `openJoystickDevice` fails with `GLFW_FALSE` is because GLFW tries to open several devices under `/dev/input` prefixed with `js` (joystick), which might not be readable or of type block, `open` fails. Therefore, I think the behaviour of seem GLFW correct here. What do you make of this @elmindreda?

**Comment by thacoon** [comment] 2016-08-22 07:04
@CaffeineViking I have not used glfw before. But the code at the top fails on two of my PCs running Arch Linux if `fs.inotify.max_user_watches` was not incremented.

**Comment by mpedantic** [comment] 2016-11-22 14:52
Hi, I have stumbled across the same problem in openSUSE 13.1. My `max_user_watches` is set to 64K and checking who's watching (as described [here](http://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached)) only shows about 20 watchers. So I didn't even bother to try increasing the limit, since I think this is not the problem. The weird thing is that up until now everything woked fine for years, but suddenly it stopped working (no HW or GLFW update, not even a reboot, one moment it works fine and couple of minutes later this). So I have two questions:

- Any idea what has changed? Ok, I get this is a hard one, but just in case...
- `glfwInit()` returns `GLFW_TRUE`, but error callback is called during the call. My application (conservatively) treats this as an error condition. Should it? I think if this is an ok state, it should be pointed out in the docs.

Cheers

**Comment by rrika** [comment] 2017-08-09 09:14
Any updates on this? I ran into the same issue. (Chromium exhausting all my file descriptors and `inotify_init1` failing consequently.)

Failure to detect joysticks shouldn't make glfwInit return false IMO.

**Comment by elmindreda** [comment] 2017-08-09 10:23
@rrika Oops, I was sure I'd fixed that. It should be fixed now with a397195d3fd14b3e94026bce684e6b5f392f5015. Thank you!

**Comment by gbuzsaki** [comment] 2017-08-14 23:08
A similar issue affects GLFW initialization on Windows Subsystem for Linux.  At this time WSL does not provide "/dev/input".  GLFW initialization fails with error:

`Failed to watch for joystick connections in /dev/input: No such file or directory
`
Hopefully this fix addresses this issue as well.

**Comment by elmindreda** [comment] 2017-10-03 01:53
I believe this issue has been resolved. The only thing in Linux joystick init that can cause initialization to fail now is if the regexp fails to compile, which should never happen™.

**Closed by elmindreda** 2017-10-03 01:53 UTC
Labels: bug, Linux
