### ISSUE TITLE
glfwSetClipboardString wrong behaviour

### ISSUE THREAD

**Issue by weenup** [glfw/glfw#961] opened 2017-03-06 23:02 UTC
hi Guys

when i calling glfwSetClipboardString with any parameters in my application and try to paste a text to another application (e.g. Gedit), nothing happens; if i paste a text to Google Chrome (in url editbox) Chrome crashes

if i calling glfwGetClipboardString in my application it returns text that i passed to glfwSetClipboardString

when i close my application i can paste text that i passed to glfwSetClipboardString to another applications correctly

OS and version: Ubuntu 16.04, GNOME desktop
GLFW release version 3.3.0

Thanks

**Comment by elmindreda** [comment] 2017-03-06 23:13
Is your application processing events when you paste into another application? Clipboard contents is transferred peer-to-peer on X11.

**Comment by weenup** [comment] 2017-03-06 23:51
My main loop looks like this now:

int cc = 0;
while (!glfwWindowShouldClose(mWindow))
{
    // my updates and drawing here
    // ...

    glfwSwapBuffers(mWindow);
    glfwPollEvents();
    logD("POLL EVENTS %d", cc++);
}

the line "POLL EVENTS" increment counter permanently (when i press Ctrl+V in Gedit)
do I need to call something else?

p.s. logD is a printf analog

**Comment by elmindreda** [comment] 2017-03-07 00:26
Do you have a complete, short example that triggers the bug?

**Comment by weenup** [comment] 2017-03-07 01:17
I took a simple example of GLFW and called glfwSetClipboardString(window, "string to be copied") there and that bug behavior kept

just run clipboard_bug binary file, focus any text editor and press Ctrl+V (nothing will happens), then close simple example and press Ctrl+V in text editor, "string to be copied" will be pasted

you can use build.sh file in archive to build application quickly, just change my paths to yours

[clipboard.zip](https://github.com/glfw/glfw/files/823019/clipboard.zip)

**Comment by tombsar** [comment] 2017-03-07 01:17
I can reproduce this with glfw's `clipboard` test program.

1. Ctrl+C in the `clipboard` window. The test reports that it has set my clipboard to "Hello GLFW World!".

2. Ctrl+V in the clipboard window reports that the clipboard contents are "Hello GLFW World!", as expected.

3. Ctrl+V in my text editor (Geany) has no visible effect (the text is not pasted, and no error is reported). After this, however, that instance of Geany will not accept pasted text from any source, even after the clipboard test is terminated.

4. Ctrl+V in Firefox causes it to freeze for several seconds, but it does seem to recover (the text is not pasted).

Debian 8.7, XFCE 4.10
GLFW current master (3.3.0)

**Comment by tombsar** [comment] 2017-03-07 12:59
Bisected to either 706868dad83b421703e50cf0c45a5abb672e6d2e (does not build for me) or ccfd6dde459f5cb2ea6c28b84c6e3e1e82a60d42.

**Comment by tombsar** [comment] 2017-03-07 13:37
Poking a bit more. It seems that the `handleSelectionRequest` function in `x11_window.c` is not being called when I try to paste into another window, although it is called twice when I close the glfw window. Not sure if I've misunderstood the code (I have no experience with X11 clipboard code), but this seems significant. Is it possible that SelectionRequest events are being filtered out somewhere, and are simply not being responded to?

**Closed** 2017-03-07 18:24 UTC
Labels: bug, verified, X11

**Comment by elmindreda** [comment] 2017-03-07 18:27
This should be fixed now with 5ae781586f1c88d977067804f28dc67844399b57 by @tombsar.

**Comment by weenup** [comment] 2017-03-09 22:12
hi Guys
thanks for your great work
pasting in another window works fine now, but i found next bug
i have launch simple example program that calling glfwSetClipboardString(window, "string to be copied");
then i have launch Gedit and press ctrl+v, string was pasted
then i have select text and on close Gedit GLFW program has been crashed with lines:

X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  18 (X_ChangeProperty)
  Resource id in failed request:  0x500009c
  Serial number of failed request:  3486
  Current serial number in output stream:  3488

if text in Gedit is not selected then program won't crash

You can see this on video in attachment
[clipboard_bug.mp4.zip](https://github.com/glfw/glfw/files/832413/clipboard_bug.mp4.zip)

**Comment by tombsar** [comment] 2017-03-10 11:49
Unfortunately I haven't been able to reproduce this new problem on my pc, so I can't debug it. I'll report back if I find anything.

**Comment by elmindreda** [comment] 2017-03-10 13:09
I couldn't reproduce it either.
