### ISSUE TITLE
Multimonitor support, clicking from one window to another, swap buffer seems to have an outdated cache?

### ISSUE THREAD

**Issue by boorishpea** [glfw/glfw#939] opened 2017-01-30 00:51 UTC
I have added multi monitor support, each cycle i loop through the windows, set their contexts then draw and swap buffers so that both windows have their contents rendered all the time.

I have noticed an odd bug, I need help assertaining if it is something with GLFW and not my code.

The window that is on the primary monitor starts with a pink screen, as soon as I start user input on that window the screen gets cleared with a different coloured background, I then move my cursor to the other monitor and click on the second monitors window, when this happens the primary monitor flickers pink once, as if it has an outdated buffer.

Can anyone help test this / shed any light on this? thank you.

**Comment by elmindreda** [comment] 2017-01-30 01:26
This is likely a duplicate of #527.

**Comment by boorishpea** [comment] 2017-01-30 14:48
Yes it appears to be the same problem, with border-less full-screen windows on multiple monitors.

**Comment by elmindreda** [comment] 2017-01-30 14:59
I'm afraid I don't have a good workaround to offer yet, then. You can use slightly smaller or slightly larger undecorated floating windowed mode windows to avoid having the OpenGL driver trigger this behavior.

**Comment by elmindreda** [comment] 2017-02-08 23:04
Closing this as a duplicate.

**Closed by elmindreda** 2017-02-08 23:04 UTC
Labels: bug, duplicate, Windows
