### ISSUE TITLE
Vulkan test segfaults (Manjaro Linux 4.8, non-static Vulkan with Intel Loader)

### ISSUE THREAD

**Issue by 0joshuaolson1** [glfw/glfw#917] opened 2016-12-14 05:44 UTC
Resizing can cause pauses of several seconds until finally (gdb):
`Thread 1 "vulkan" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()`

The window remains until I can kill it. This happens on master and 3.2.1.

I don't know if the
```
anv_image.c:190: FINISHME: Implement gen7 HiZ
gen7_cmd_buffer.c:242: FINISHME: Implement Gen7 HZ ops
```
are related.

**Comment by elmindreda** [comment] 2016-12-14 14:38
What is the output of `glfwinfo`?

**Comment by 0joshuaolson1** [comment] 2016-12-14 15:43
```
GLFW header version: 3.3.0
GLFW library version: 3.3.0
GLFW library version string: "3.3.0 X11 GLX EGL clock_gettime /dev/js"
OpenGL context version string: "3.0 Mesa 13.0.2"
OpenGL context version parsed by GLFW: 3.0.0
OpenGL context flags (0x00000000):
OpenGL context flags parsed by GLFW:
OpenGL robustness strategy (0x00008261): none
OpenGL robustness strategy parsed by GLFW: none
OpenGL context renderer string: "Mesa DRI Intel(R) Ivybridge Mobile "
OpenGL context vendor string: "Intel Open Source Technology Center"
OpenGL context shading language version: "1.30"
OpenGL framebuffer:
 red: 8 green: 8 blue: 8 alpha: 8 depth: 24 stencil: 8
 samples: 0 sample buffers: 0
 accum red: 0 accum green: 0 accum blue: 0 accum alpha: 0 aux buffers: 0
Vulkan loader: available
Vulkan required instance extensions: VK_KHR_surface VK_KHR_xcb_surface
WARNING: Ivy Bridge Vulkan support is incomplete
Vulkan integrated GPU device: "Intel(R) Ivybridge Mobile"
```
There is a warning there.

**Comment by elmindreda** [comment] 2016-12-15 13:39
Cannot reproduce on X11 with Nvidia's Vulkan ICD. The warning is likely relevant.

**Comment by elmindreda** [comment] 2017-01-16 18:07
I have a very similar setup now. Will try to reproduce.

**Comment by linkmauve** [comment] 2017-01-16 19:41
This is most likely a duplicate of this driver bug: https://bugs.freedesktop.org/show_bug.cgi?id=99196

**Comment by elmindreda** [comment] 2017-03-27 18:15
Closing this as an external bug in the unfinished Intel Vulkan driver. Please re-open or open a new one if problems occur with a fully implemented version.

**Closed by elmindreda** 2017-03-27 18:15 UTC
Labels: bug, external, Intel, Vulkan, waiting, X11
