### ISSUE TITLE
Windows are transparent when building with GLFW_USE_WAYLAND=ON

### ISSUE THREAD

**Issue by egaban** [glfw/glfw#1803] opened 2020-11-06 13:30 UTC
When using GLFW compiled with -DGLFW_USE_WAYLAND=ON, windows are weird and transparent both on Xorg and wayland. Also, the framebuffer does not get cleared. I'm attaching a screenshot and a picture taken from my phone (because when taking a screenshot the framebuffer does get cleared).
![cube](https://user-images.githubusercontent.com/18158965/98370942-219b5a80-201a-11eb-90ed-6edc1f1e097f.png)

This was first noted on Fedora, here is a bug report I recently opened: https://bugzilla.redhat.com/show_bug.cgi?id=1894716

I also tried this with gentoo and a friend of mine had the problem with Ubuntu and they all had the same problem

**Comment by artyomd** [comment] 2020-11-06 18:44
I think I am currently experiencing the same issue. Except I don't have any issues with framebuffer and transparency. I have the same weird title bar and the resizing of the window works very strangely. Also, I am unable to init glew with the OpenGL context of the glfw window, but the Vulkan is somehow working with this strange error message
```
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
```

Btw, here is my environment:

os: Fedora 33 workspation
cpu: intel core-i7-6500U (no extra dedicated gpu)
gpu drivers: mesa 20.2.1-2.fc33
glfw: 1:3.3.2-7.fc33
windowing system: wayland

If anyone wants to reproduce the issue here is the project that I am trying to run: https://github.com/artyomd/GPU-Playground
Also the last time I run the project was before upgrading to fedora 33 and everything was fine.

@egaban if you are saying that the bugs are from Wayland support, that means that the glfw that is in fedora 32 repositories, doesn't have Wayland support? Also I don't remember updating the glfw version and the version 3.3.2 was released in january.

**Comment by artyomd** [comment] 2020-11-06 19:11
Also, I forgot to mention that today the first time I run I got the following error:
`glfw error 65544: Wayland: Focusing a window requires user interaction`
And the strange thing is that this error message I got when I was trying to create a window. Then I added this hint:
`glfwWindowHint(GLFW_FOCUSED, GLFW_FALSE);`
and after that, the buggy window was shown

**Comment by artyomd** [comment] 2020-11-06 19:20
I have tried the version 3.3.2-2.fc32 and everything works as usual. After that, I found this: https://www.mail-archive.com/package-announce@lists.fedoraproject.org/msg263495.html and this confirms that the major difference between version 3.2.2-2fc32 and 3.2.2-7fc33 is that the last one is built with -DGLFW_USE_WAYLAND=ON

**Comment by egaban** [comment] 2020-11-06 20:39
> I think I am currently experiencing the same issue. Except I don't have any issues with framebuffer and transparency. I have the same weird title bar and the resizing of the window works very strangely. Also, I am unable to init glew with the OpenGL context of the glfw window, but the Vulkan is somehow working with this strange error message

I'm experiencing exactly the same resizing issue too.

> @egaban if you are saying that the bugs are from Wayland support, that means that the glfw that is in fedora 32 repositories, doesn't have Wayland support? Also I don't remember updating the glfw version and the version 3.3.2 was released in january.

I don't know about the F32 glfw, but the one in F33 repository got a recent update enabling wayland builds (https://src.fedoraproject.org/rpms/glfw/c/9765052882702457a1c1f85e9c44602f3cf4158b?branch=master)

Before that update everything worked fine

As for the warnings, I didn't get any

**Comment by artyomd** [comment] 2020-11-14 18:45
The warning that I have talked about earlier, turned out that doesn't have any connection with glfw.
Also, I want to mention that pr #1693 is fixing this issue.

**Comment by egaban** [comment] 2020-11-18 01:31
> The warning that I have talked about earlier, turned out that doesn't have any connection with glfw.
> Also, I want to mention that pr #1693 is fixing this issue.

Good to hear that. Hope it fixes the transparent windows too

**Comment by Zamundaaa** [comment] 2021-01-08 02:05
>I think I am currently experiencing the same issue. Except I don't have any issues with framebuffer and transparency. I have the same weird title bar and the resizing of the window works very strangely. Also, I am unable to init glew with the OpenGL context of the glfw window, but the Vulkan is somehow working with this strange error message

Using Vulkan, resizing is also very strange for me, but that looks like a KWin bug in my case (directly when beginning to resize the window position jumps and there's a ghost window appearing on the old position).

Vulkan windows are also opaque for me, OpenGL ones are transparent (the difference is probably that you explicitly state the transparent-ness for the VkPipeline).
Oddly with Vulkan it also looks like it jumps frames back and forth (like some frames are swapped in time). Does anyone else experience that here as well?

>Good to hear that. Hope it fixes the transparent windows too

I tested it and it does unfortunately not make any difference.

**Comment by linkmauve** [comment] 2021-12-14 17:41
This is now fixed, when using drivers which expose the `EGL_EXT_present_opaque` extension, such as Mesa.

**Closed** 2021-12-14 17:40 UTC
Labels: Wayland
