### ISSUE TITLE
Some issues that I found with Wayland + Vulkan

### ISSUE THREAD

**Issue by warriormaster12** [glfw/glfw#1914] opened 2021-06-10 13:59 UTC
So here's a list of issues that I found while test driving wayland with my Vulkan project.

Here's a link to the project if you want to test Wayland with Vulkan: https://github.com/warriormaster12/OdinEngine
Anyways, 
the issues that I noticed are: 
- resizing when dragging from window's corner doesn't work.
- mouse capturing works but doesn't hide mouse cursor itself from view. 
- Fps is locked for some reason to Monitor's refresh rate(in this case 60 Hz).

Hopefully this helps in some way, shape or form. Let me know if you need any additional info about Wayland + Vulkan bugs. 

Specs: 
- Amd Ryzen 5 2500U with Vega 8 GPU
- 8GB ddr4 ram 
- Os: Arch Linux 
- DE: KDE Plasma 5.22

**Comment by TheBrokenRail** [comment] 2021-06-15 15:52
All of these except the FPS locking also happen to me on my Ryzen 3700U on Ubuntu 20.04.

**Comment by warisb** [comment] 2021-06-18 18:43
I believe https://github.com/glfw/glfw/pull/1899 should fix the cursor hiding issue. :) please help vote for it

**Comment by warriormaster12** [comment] 2021-06-19 08:21
@warisb tried running your patch on my project and it doesn't hide the mouse cursor, it just flickers once and stays visible.

**Comment by warriormaster12** [comment] 2021-06-19 08:33
Did you test this with Vulkan?

**Comment by warriormaster12** [comment] 2021-06-19 08:38
@warisb Tested with one of my OpenGl projects and it works with but with Vulkan it doesn't

**Comment by NoMore201** [comment] 2021-07-17 15:38
I'm quite sure that wayland FPS is capped to screen refresh rate by design. There is ongoing discussion to implement async page flip here https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/65

**Comment by warriormaster12** [comment] 2021-07-21 12:00
@NoMore201 didn't know about that. Now I'm curious how XWayland handles fps since I've seen games running over 60fps under it.

**Comment by Zamundaaa** [comment] 2021-09-06 13:13
@NoMore201 Wayland does not limit the rate at which surface updates are committed. It currently enforces the `mailbox` presentation mode (which the MR intends to optionally change to `immediate`), not `fifo`.

**Comment by elmindreda** [comment] 2024-02-04 16:00
> mouse capturing works but doesn't hide mouse cursor itself from view.

This appears to have been fixed as well now. Not sure exactly when; there's been a lot of Wayland-related fixes. Thank you for the bug reports!

**Closed by elmindreda** 2024-02-04 16:00 UTC
Labels: bug, verified, Wayland, Vulkan, input
