### ISSUE TITLE
"Laggy" mouse movement with GLFW_CURSOR_DISABLED 

### ISSUE THREAD

**Issue by sippeangelo** [glfw/glfw#691] opened 2016-01-14 21:05 UTC
Tested on Windows 8.1 and Windows 10, MSVC14.

When `GLFW_CURSOR_DISABLED` is set, it seems that the cursor position returned by GLFW doesn't always update. I felt this as my camera movement would sometimes make a small jump while moving smoothly. I decided to test it more thoroughly and I've come to the conclusion that when two identical mouse deltas are received by whatever goes on under the hood of GLFW, it doesn't report it until the next mouse event! This applies to both `glfwGetCursorPos` and `glfwSetCursorPosCallback`.

I set up an AutoHotkey script to verify this, where a button on my keyboard would move my mouse 100 pixels on the x-axis instantly. The test and its output went down like this:

```
glfwGetCursorPos returns 0 
AutoHotkey moves 100
glfwGetCursorPos returns 100
GLFWcursorposfun reports 100
AutoHotkey moves 100
glfwGetCursorPos returns 100
GLFWcursorposfun isn't called at all
AutoHotkey moves 100
glfwGetCursorPos returns 300
GLFWcursorposfun reports 300
AutoHotkey moves 100
glfwGetCursorPos returns 400
GLFWcursorposfun reports 400
AutoHotkey moves 100
glfwGetCursorPos returns 400
GLFWcursorposfun isn't called at all
AutoHotkey moves 100
glfwGetCursorPos returns 600
GLFWcursorposfun reports 600
...
```

While if I alternated between a 100 pixel movement and a 101 pixel movement, it would go like this:

```
glfwGetCursorPos returns 0 
AutoHotkey moves 100
glfwGetCursorPos returns 100
GLFWcursorposfun reports 100
AutoHotkey moves 101
glfwGetCursorPos returns 201
GLFWcursorposfun reports 201
AutoHotkey moves 100
glfwGetCursorPos returns 301
GLFWcursorposfun reports 301
AutoHotkey moves 101
glfwGetCursorPos returns 402
GLFWcursorposfun reports 402
AutoHotkey moves 100
glfwGetCursorPos returns 502
GLFWcursorposfun reports 502
AutoHotkey moves 101
glfwGetCursorPos returns 603
GLFWcursorposfun reports 603
...
```

So this causes a rather jittery behavior that doesn't exist with `GLFW_CURSOR_HIDDEN` nor `GLFW_CURSOR_NORMAL`. I don't know why this happens, so hopefully you could shed some light on the matter. 

I'm not sure if AutoHotkey is a great way to test this, but I'm confident there is some mouse jitter going on when using `GLFW_CURSOR_DISABLED` that doesn't exist in other modes and when resetting the mouse position to the middle of the screen each frame manually.

**Comment by tombsar** [comment] 2016-01-19 16:29
This is worrying. How repeatable are the results? I can't see anything in the glfw code that would obviously cause this, but it might be something subtle.

**Comment by haikarainen** [comment] 2016-02-21 10:39
This looks highly suspicious https://github.com/glfw/glfw/blob/master/src/input.c#L198 

Couldn't that double check get precision issues with rounding etc, and effectively report false positives?

**Comment by shurcooL** [comment] 2016-02-21 10:42
An `== 0.0` check for `double` is very hard to hit `true` unless the value is actually exactly `0.0`, so that seems unlikely.

**Comment by haikarainen** [comment] 2016-02-21 11:19
shurcooL: Unlikely yes, impossible no.

Anyway, I tried to reproduce this using autohotkey v1.1.23.01, MSVC14, latest GLFW git and Windows 10 and I couldn't. x64 builds.

Although I did notice something, moving the cursor using autohotkey with GLFW_CURSOR_DISABLED  will only call the callback once in a row for me. I have to move the mouse manually to "reset" it and have it work for another AHK-macro-keypress.  This makes me believe that AHK is the issue and **not ** GLFW, and that sippeangelos laggy mouse movements has another cause.

Check this gist for my unreproducable example: https://gist.github.com/haikarainen/140a523a7a99b4cd7cbc

**Comment by tombsar** [comment] 2016-02-21 16:51
@haikarainen I don't believe any rounding occurs for equality checks on floating point numbers. It might be interesting to see if the function is ever called with x and y both exactly zero, and under what circumstances, but not passing those events on to the client callback is imo the right thing to do. In fact I wonder why the test is only in the `GLFW_CURSOR_DISABLED` block, and not outside?

**Comment by haikarainen** [comment] 2016-02-22 18:10
@tombsar I believe you are wrong with regards to double comparisons.. DBL_MIN (defined in float.h) defines the lowest possible value for a double (higher than 0.0). What would happen if a value is between 0.0 and DBL_MIN? It's pretty commonly known that comparisons between floats/doubles are unreliable to some degree.

**Comment by tombsar** [comment] 2016-02-22 18:25
@haikarainen It is very common for two numbers that you think *should* be equal to test as unequal, but not so much the other way around. I am struggling to find a reliable source right now, but I am fairly sure even denormal doubles will test as unequal to 0.0.

**Comment by haikarainen** [comment] 2016-02-24 03:44
Yes I agree @tombsar, my suspicion was mainly based around the circumstances of the function and the issue at hand. With a reproducable example it would be very easy to test and verify though.

**Comment by ArcaneEngineer** [comment] 2016-07-10 18:15
I'm not sure if this is related, but I'm going through some unfortunate issues after migrating from Windows / Ubuntu dev environment to Debian Jessie. What happens now is that every time I hold a key down - any key, and whether it's being used in my code or not - `glfwGetCursorPos` (and `glfwSetCursorPosCallback`) start jumping by a factor of 10 or so more than the usual mouse deltas. The moment I let go of the key, things get back to normal with the mouse.

**Comment by ArcaneEngineer** [comment] 2016-07-10 20:11
Just confirmed that this happens in the wave demo, too, i.e. completely independent of my own code. Let me know if you need any details about my system.

**Comment by ArcaneEngineer** [comment] 2016-07-17 14:39
My problem was not caused by GLFW.

SDL has same problem on my dev system. Does not appear to be a hardware issue (?) as plugging in a different keyboard via USB works fine. Likely a Debian 8 config issue. Copied executable to my Ubuntu box from Debian dev machine - works perfectly there (that Ubuntu is based on an older version of Debian, 7 I think).

**Comment by tombsar** [comment] 2016-07-17 16:28
@elmindreda We haven't had confirmation from @sippeangelo that his issue has been resolved. I'm not convinced @ArcaneEngineer's similar issue is actually the same.

**Comment by elmindreda** [comment] 2016-07-17 18:34
I rewrote the disabled cursor paths for all platforms between February and now both to fix a number of possibly related issues and to cut down on complexity and internal state. If someone has the means, please check whether this issue can still be reproduced.

**Comment by elmindreda** [comment] 2017-03-27 18:12
I'm assuming there are no further problems. Closing this.

**Closed by elmindreda** 2017-03-27 18:12 UTC
Labels: bug, waiting, Windows
