### ISSUE TITLE
glfwGetVideoModes takes couple seconds

### ISSUE THREAD

**Issue by sagaceilo** [glfw/glfw#550] opened 2015-07-07 16:49 UTC
Hi :)

As in the title. glfwGetVideoModes is taking up to 20 seconds while collecting all videomodes for given monitor. While I have 3 monitors, whole listing process takes one minute ;)

I'll investigate this in a while. My spec: Win10 (10162) x64 . Working on the newest master branch of glfw.

**Comment by elmindreda** [comment] 2015-07-07 17:17
Oh, great. This is caused by bb50368d55eab508dc77e3cb0de9e2c5fd15ac7e.

Please fight it out with #350 and let me know who won.

**Comment by sagaceilo** [comment] 2015-07-07 18:57
Yup, commenting out this changelist made listing modes balizng fast again. Googled a bit and actually there is no other solution for cheking if given mode is truly valid. There is a bpp check that discards < 15 bpp, the most ugly and hacky way would be add there some extra conditions like < 50 Hz etc.

BTW. I had no modes that ChangeDisplaySettingsExW would consider as unvalid.

**Comment by elmindreda** [comment] 2015-08-18 22:18
If anyone else experiences this issue, please speak up, even if just with a :hand:.

**Comment by wintertime** [comment] 2015-08-19 13:18
I didn't try it, but couldn't you at least somewhat speed it up by not doing the slow test first and moving its code after the faster running tests excluded some unusable modes?

**Comment by elmindreda** [comment] 2015-08-19 15:40
@sagaceilo Please post the output of `monitors` on your machine. I'll see about mitigating this before 3.1.2.

**Comment by sagaceilo** [comment] 2015-08-20 09:07
I'm on vacations since Saturday. When I come back, I'll post log here :)

**Comment by theagentd** [comment] 2015-09-06 02:07
"If anyone else experiences this issue, please speak up, even if just with a :hand:."

:hand: We have this problem. I have 3 monitors that I get display modes for, and it takes 1750ms per monitor, i.e. ~5 seconds for 3 monitors.

**Comment by elmindreda** [comment] 2015-09-18 13:46
I'd be very interested in the output of [monitool](/elmindreda/monitool) on your machines.

**Comment by theagentd** [comment] 2015-09-18 13:48
I don't have a build environment for C++ set up... Any chance I could get an executable? ._.

**Comment by elmindreda** [comment] 2015-09-18 14:01
@theagentd Sure, if you trust [that sort of thing](http://www.dreda.org/temp/monitool.zip).

**Comment by theagentd** [comment] 2015-09-19 09:19
Is there a specific reason why I shouldn't trust you that I should be aware of?

http://pastebin.com/3znFWgj8

**Comment by shurcooL** [comment] 2015-09-19 17:39
The link is not https so there's a possibility of a MITM. I think @elmindreda meant that as a general disclaimer when downloading binaries from the internet, you should be careful doing so.

**Comment by elmindreda** [comment] 2015-09-19 20:45
Everything @shurcooL said and it was built on a Windows machine.

**Comment by theagentd** [comment] 2015-09-19 23:29
Did the data I posted help? Do you need anything else?

**Comment by elmindreda** [comment] 2015-09-20 13:29
@theagentd It helped immensely. Help with testing once I have some code would be great, but other than that I have what I need.

**Comment by elmindreda** [comment] 2015-09-20 15:09
Please see if the optimistically named `fast-mode-enum` works better on your systems.

**Comment by elmindreda** [comment] 2015-09-20 15:32
@sagaceilo I'd love to see a [monitool](https://github.com/elmindreda/monitool) output from your system as well, if possible.

**Comment by sagaceilo** [comment] 2015-09-20 19:07
Here you go: http://pastebin.com/h39AuAzA :)

**Comment by elmindreda** [comment] 2015-09-20 20:41
@sagaceilo Did it not compile for you? It works fine with Community Edition 2015. The editor doesn't understand the anonymous struct, but the compiler does.

**Comment by elmindreda** [comment] 2015-10-02 13:48
Did anyone test the `fast-mode-enum` branch?

**Comment by theagentd** [comment] 2015-10-05 18:54
I have finally tested it. Mode querying now takes a little under 400ms instead of 1750ms for each monitor, a massive improvement. That's fast enough IMO.

**Comment by elmindreda** [comment] 2015-10-06 17:25
@theagentd Thank you! It's still a horribly long time and I'll look further into it for 3.2, but I'll consider this non-blocking for 3.1.2 then.

**Comment by theagentd** [comment] 2015-10-06 21:19
Yes, that will be fine! Thanks for the fix!

**Comment by elmindreda** [comment] 2015-10-26 00:44
@sagaceilo Is the code in 3.1.2 and `master` fast enough for your needs?

**Comment by sagaceilo** [comment] 2015-10-26 18:45
Yes, works like a charm :) Thank You !

**Closed** 2015-10-26 18:52 UTC
Labels: bug, verified, Windows
