### ISSUE TITLE
Cocoa IME input did not composited.

### ISSUE THREAD

**Issue by ageldama** [glfw/glfw#607] opened 2015-09-15 23:25 UTC
In OSX, IME input didn't composited. (ㅎ,ㅏ,ㄴ ...)
![fail osx korean input composited](https://cloud.githubusercontent.com/assets/54128/9892688/29277d16-5c4c-11e5-8415-a4fd614aad0e.png)

In Linux + XIM, IME composition is correct. ("한" = ㅎ+ㅏ+ㄴ, ...)
![ok linux xim korean input composited](https://cloud.githubusercontent.com/assets/54128/9892689/2927ccb2-5c4c-11e5-9903-ee91aefe1c0b.png)

Tested with 
.. commit 40da56fbf79d74bfbda6929432fc8cfed3546919 (OSX, Linux both.)
.. [test application](https://github.com/ageldama/glfw3-unicode)

Thanks.

**Comment by elmindreda** [comment] 2015-09-16 00:53
Duplicate of #456.

**Closed by elmindreda** 2015-09-16 00:53 UTC
