### ISSUE TITLE
  Could NOT find X11 (missing: X11_X11_LIB)

### ISSUE THREAD

**Issue by jinfagang** [glfw/glfw#2091] opened 2022-04-29 03:35 UTC
Could NOT find X11 (missing: X11_X11_LIB)

I have already installed libx11-dev libxorg-dev

**Comment by elmindreda** [comment] 2022-04-29 11:54
This is a duplicate of issue #1957.

**Closed** 2022-04-29 11:55 UTC
Labels: bug, duplicate, X11, external, cannot reproduce, build

**Comment by elmindreda** [comment] 2022-04-29 12:01
Please don't create duplicate issues.
