### ISSUE TITLE
Inconsistent Callback behavior on window resize event between Windows and Linux

### ISSUE THREAD

**Issue by poli0048** [glfw/glfw#1613] opened 2019-12-18 00:19 UTC
On resizing a window from the left or top edge, or the top-left corner GLFW will:
 - On Windows trigger both ImGui_ImplGlfw_WindowSizeCallback() and ImGui_ImplGlfw_WindowPosCallback()
- On Linux trigger only ImGui_ImplGlfw_WindowSizeCallback()

On Linux this can create problems for programs that assume any change in window origin location will be accompanied by a ImGui_ImplGlfw_WindowPosCallback(), since resizing from the top or left edge, or the top-left corner will change the origin location for the window. Maximizing a window will also change the origin location (not sure what callbacks this triggers).

It isn't clear to me which behavior is "correct", but it should be consistent across platforms. I am running GLFW master - built a few hours ago.

**Comment by poli0048** [comment] 2019-12-19 19:47
I have some additional info to add to this. The behavior is not consistent on Linux:
System 1: Debian Buster with Gnome 3.32 on X11 (Not Wayland)
System 2: kwin_x11 (I don't have any more details)

On system 1 only ImGui_ImplGlfw_WindowSizeCallback() is triggered. On system 2, both ImGui_ImplGlfw_WindowSizeCallback() and ImGui_ImplGlfw_WindowPosCallback() are triggered on a left or top edge or top-left corner resize event.

**Comment by elmindreda** [comment] 2020-01-01 16:42
Thank you for reporting this. This should be fixed now with fe57e3c2921a1901390534e1e51053df70b5644b.

This was a bug in the X11 implementation caused by not correctly following [ICCCM 4.1.5](https://tronche.com/gui/x/icccm/sec-4.html#s-4.1.5). Not all window managers send synthetic events during a resize and GLFW was discarding the position of the real ones.

**Closed** 2020-01-01 16:42 UTC
Labels: X11, bug, verified
