### ISSUE TITLE
Segfault when calling glfwPollEvents() on Mac OS X with window height = 0

### ISSUE THREAD

**Issue by nippoo** [glfw/glfw#481] opened 2015-03-26 15:43 UTC
Steps to reproduce:

- Create any window.
- Resize to 0 height.
- Call `glfwPollEvents()`

Mac OS X 10.10, Retina MacBook Pro 15", Python 3.4

**Comment by elmindreda** [comment] 2015-03-26 15:53
This is a duplicate of #443.

**Closed by elmindreda** 2015-03-26 15:53 UTC
