### ISSUE TITLE
OSX 10.14 (Mojave) Window does not draw after being created until it is moved.

### ISSUE THREAD

**Issue by mokafolio** [glfw/glfw#1361] opened 2018-10-17 00:26 UTC
Hi,

This might be related to: https://github.com/glfw/glfw/issues/1357

50% of the time, the glfw window stays blank on Mojave until it is moved for the first time (the window just stays white). I am not sure if that is helpful but I remember SDL2 initially had the same issue on Mojave but it's fixed in their master. It even happens with a bare bones glfw example that just clears the framebuffer to a certain color.

Best,
Moka

**Comment by ofZach** [comment] 2018-10-17 01:58
if helpful, the SDL2 issue: 
https://bugzilla.libsdl.org/show_bug.cgi?id=4272

PR that addresses this
https://github.com/glfw/glfw/pull/1346

**Comment by dmitshur** [comment] 2018-10-19 03:08
Thanks for the report. This is a duplicate of #1334.

**Closed by dmitshur** 2018-10-19 03:08 UTC
Labels: duplicate
