### ISSUE TITLE
Support for window size limits

### ISSUE THREAD

**Issue by xanather** [glfw/glfw#555] opened 2015-07-15 03:45 UTC
Is it possible to have such a function (doesn't have to be exact name)?

On Windows WM_GETMINMAXINFO wnd msg needs to be handled, not sure about other platforms.

**Comment by elmindreda** [comment] 2015-07-15 09:12
This is already in `devel` and will be in 3.2.

**Comment by elmindreda** [comment] 2015-07-15 09:14
The function is `glfwSetWindowSizeLimits`.

**Comment by xanather** [comment] 2015-07-15 10:37
Okay thanks for that, I will compile the dev source for now so I can use the function straight away

**Comment by xanather** [comment] 2015-07-16 14:17
I think the devel branch is unstable, I am unable to create a window, glfwCreateWindow always crashes me. Compiling glfw with exact same methods for the master branch is fine.

**Comment by elmindreda** [comment] 2015-07-16 14:40
It is, yes.

**Comment by theagentd** [comment] 2015-09-06 02:24
This is something we need to ensure our game window isn't made too small. Currently adding a size listener which calls glfwSetWindowSize() if the size is too small works, but is hackish.

**Closed** 2015-10-18 15:19 UTC
Labels: enhancement, OS X, Windows, X11

**Comment by theagentd** [comment] 2015-10-26 17:42
Can confirm that this is working as intended. Thanks!
