### ISSUE TITLE
Joystick connections/disconnections not detected

### ISSUE THREAD

**Issue by jsparksml** [glfw/glfw#1218] opened 2018-02-22 23:11 UTC
This is on the latest Sierra and High Sierra, with an Xbox 360 controller connected to a USB-C port (using a USB-A to USB-C adapter) on a MacBook Pro 2017 model.

The controller must be connected on application startup (found using _glfwJoystickPresent_). Any controllers connected after startup are not detected (the callback is not triggered), and neither are disconnections of controllers detected initially (e.g., the joystick callback does not appear to function on MacOS).

It seems that a controller must be connected before _glfwInit_ is called for it to be detected. I was able to work around this error by re-initializing GLFW in an update loop every second (this application is solely for gamepad input). Using this method, I can successfully detect connections and disconnections (though I must manually call _glfwJoystickPresent_ during this phase for known controllers to decide if they have been disconnected.

**Comment by elmindreda** [comment] 2018-02-22 23:59
> this application is solely for gamepad input

For joystick connection events to be delivered on macOS (and Windows), the main thread message queue must be polled. Try calling `glfwPollEvents` at regular intervals instead of reinitializing the whole library.

**Comment by jsparksml** [comment] 2018-02-28 19:12
`glfwPollEvents` is already being called in the update loop. I still have to re-initialize the library for the connected state of joysticks to change.

**Comment by elmindreda** [comment] 2018-03-01 01:58
Apologies. I should have run code before replying.

This should be fixed now with 77879736af21941a522e538a87af787fe86c648b.

**Closed by elmindreda** 2018-03-01 01:58 UTC
Labels: bug, macOS, verified

**Comment by TheDonsky** [comment] 2021-05-21 15:03
Have similar problem on Windows... Disconnection is reported in the callback passed through glfwSetJoystickCallback, but there are no reconnections...

**Comment by elmindreda** [comment] 2021-06-25 18:56
@TheDonsky That sounds like it might be a separate bug. If it's still happening, please open an issue for it. I'll need the version of GLFW and Windows and if possible the controller model and if it's wired or not.

**Comment by TheDonsky** [comment] 2021-06-27 17:16
> @TheDonsky That sounds like it might be a separate bug. If it's still happening, please open an issue for it. I'll need the version of GLFW and Windows and if possible the controller model and if it's wired or not.

Controller is a regular Xbox 360 wireless controller, with the standard receiver, Microsoft sold;
Windows: Build 19043.1052 (Windows 10 Home);
GLFW: 3.3.2 

Exact "symptoms" are as follows:
I have a functioning input, as long as the joystick is already connected when I first call glfwInit(); 
If I disconnect the controller, glfwSetJoystickCallback correctly reports the event and, naturally, my input module goes silent for the device. 
Problem starts, when I reconnect the controller or simply connect it after glfwInit: glfwSetJoystickCallback reports nothing and glfwJoystickPresent/glfwGetGamepadState calls do not give me anything useful any more.

Project is not "tied" to the above version, so if it's likely fixed in the latter version, I can test with the new build without too many complications; Also, I've tested the same on my linux(Ubuntu) machine and the same code works perfectly fine there (same version). So, this makes it a Windows-only issue for me

For additional insights, feel free to look at the exact code, in case it helps: 
[https://github.com/TheDonsky/Jimara/blob/main/__Source__/Jimara/OS/Window/GLFW/GLFW_Window.cpp](url) (line 34 for glfwSetJoystickCallback);
[https://github.com/TheDonsky/Jimara/blob/main/__Source__/Jimara/OS/Window/GLFW/GLFW_Input.cpp](url) (line 359 onward for gamepad state);
Behavior can be observed from any test case, that creates a window and displays some amount of 3d graphics (for example, [https://github.com/TheDonsky/Jimara/blob/main/__Source__/Jimara-Tests/Components/MeshRendererTest.cpp](url) but I think you probably won't need to build it, but anyway...)

**Comment by elmindreda** [comment] 2021-06-28 23:14
@TheDonsky I can't reproduce that with the controllers I have but it sounds like a real bug, although different from this one. Please open a new issue for it. You description above is really good so you can re-use that.

**Comment by TheDonsky** [comment] 2021-06-29 06:41
@elmindreda I opened an issue: https://github.com/glfw/glfw/issues/1926
I also added a link to a screen recording of the bug "in action"; will test with a newer GLFW build as well when possible and report if it's fixed

**Comment by TheDonsky** [comment] 2021-06-29 06:52
Update: I checked 3.3.4 binaries as well and the issue persists
