### ISSUE TITLE
Add Joystick rumble/vibration support

### ISSUE THREAD

**Issue by Klotzi111** [glfw/glfw#1042] opened 2017-07-08 15:33 UTC
it would be nice if you could control all rumblers from a Joystick/Gamepad individually.

**Comment by elmindreda** [comment] 2017-07-08 21:40
Agreed! See #57 for progress. Everything is _finally_ ready to start working on this (#900 was resolved yesterday).

**Comment by elmindreda** [comment] 2017-07-09 10:46
Closing this as a duplicate of #57.

**Closed by elmindreda** 2017-07-09 10:46 UTC
Labels: duplicate, enhancement
