### ISSUE TITLE
Compile fails if you define GLFW_EXPOSE_NATIVE_NSGL but not GLFW_EXPOSE_NATIVE_COCOA

### ISSUE THREAD

**Issue by jherico** [glfw/glfw#1349] opened 2018-10-08 19:49 UTC
https://github.com/glfw/glfw/blob/cc805c09630a4b0b273cb5475a3bead706daa09d/include/GLFW/glfw3native.h#L111

The `id` typedef is only defined in the `GLFW_EXPOSE_NATIVE_COCOA` block.  If you are only interested in the NSGLcontext and define `GLFW_EXPOSE_NATIVE_NSGL` then the return value of `glfwGetNSGLContext` is an undefined type.

**Comment by tombsar** [comment] 2018-10-09 08:43
This is actually documented/intended behaviour (http://www.glfw.org/docs/latest/group__native.html); you are required to define `GLFW_EXPOSE_NATIVE_COCOA` if you want to use the native access header on MacOS. I suppose the question is whether there is a good reason for us to relax that requirement.

**Comment by jherico** [comment] 2018-10-10 00:18
It's a reasonable condition I suppose, but begs the question as to why the various context declarations aren't guarded by both the window system API define and the GL context define.... i.e. `#if defined(GLFW_EXPOSE_NATIVE_NSGL) && defined(GLFW_EXPOSE_NATIVE_COCOA)`.  That would make it more clear that the behavior was intended _and_ prevent the compile error if you only defined the context value.

**Comment by elmindreda** [comment] 2018-10-24 15:22
There doesn't seem to be a good reason _not_ to allow exposing only access to platform-specific context API handles, except that it'll be harmlessly useless for GLX, so I'll make that work instead.

**Comment by elmindreda** [comment] 2018-11-23 13:07
This was fixed with 6a199c1f5e4c320c73ce28be6480c7a9b6a13692.

**Closed by elmindreda** 2018-11-23 13:07 UTC
Labels: Windows, X11, enhancement, macOS
