### ISSUE TITLE
GLFW_CURSOR_HIDDEN does not hide cursor

### ISSUE THREAD

**Issue by Simmesimme** [glfw/glfw#428] opened 2015-01-22 18:30 UTC
When using GLFW 3.1 with Ubuntu, hiding the mouse cursor via glfwSetInputMode() does not have any effect. The same code does hide the mouse cursor under Windows.

With GLFW 3.0, everything worked as supposed. Is this a bug?

**Comment by elmindreda** [comment] 2015-01-22 21:28
This is a duplicate of #309.

**Closed by elmindreda** 2015-01-22 21:28 UTC
Labels: bug, duplicate, X11
