### ISSUE TITLE
No way to access the correct DPI on X11

### ISSUE THREAD

**Issue by kovidgoyal** [glfw/glfw#1019] opened 2017-05-19 16:03 UTC
Modern toolkits under X11 generally use Xft.dpi resource to get the "logical" screen dpi. If that does not exist, then the physical dpi as reported by xrandr is used. 

In order for text sizes in glfw applications specified in pts to match text sizes in other applications on the desktop, the logical dpi needs to be used rather than the physical one. There should be an API to query this value, as far as I can see there isn't one at the moment. 

As evidence for my claim that modern toolkits use Xft.dpi, see Qt source code for the logicalDpi function:

https://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platforms/xcb/qxcbscreen.cpp?id=b393641888f18e3accf094c91808e2189c2138cc#n478

you can see that it uses m_forcedDpi, if available. m_forcedDpi is set from Xft.dpi, here:
https://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platforms/xcb/qxcbscreen.cpp?id=b393641888f18e3accf094c91808e2189c2138cc#n860

I'm not that familiar with DPI handling on other platforms, but alt least on X11, there needs to be a way to query a Monitor object for its logical DPI. Currently I hack around this in my application by using xrdb but 
that is less than optimal.

EDIT: Another resource that mentions Xft.dpi: https://wiki.archlinux.org/index.php/HiDPI#X_Resources

**Comment by felipefs** [comment] 2017-05-19 16:11
A little research, and I found that it's easy to get the dpi on X11 using these functions: https://linux.die.net/man/3/displaywidthmm

I will make an implementation and send a PR.

**Comment by kovidgoyal** [comment] 2017-05-19 17:04
DisplayWidthMM is not useful - that information is already available in glfw in the monitor object via getMonitorPhysicalSize. However, the DPI calculated using getMonitorPhysicalSize often does not match the value set via Xft. Usually desktop environments/startup scripts, set Xft.dpi to a simple multiple of 96. For example on my 4K display, it is set to 192, while the actual physical dpi as reported by xrandr is 160. All non-glfw applications on my desktop use 192 as the dpi, not 160. 

What should be done is query the xrdb database to get the Xft.dpi resource. The equivalent of doing

xrdb -query | grep Xft.dpi

For an example of doing that, look at the qxcbscreen.c source file I linked to earlier. 

Also, while currently in X11 there is no per-monitor dpi there will likely be a per monitor dpi in the future with wayland. So the API you create should take a monitor object as an argument, which will be currently unused.

**Comment by linkmauve** [comment] 2017-05-19 17:12
HiDPI is already properly supported on Wayland, you can use it by building GLFW with `-DGLFW_USE_WAYLAND=ON`.

**Comment by kovidgoyal** [comment] 2017-05-19 17:45
How do I get the same DPI that other applications are using on wayland?

**Comment by felipefs** [comment] 2017-05-19 18:07
Are you using C or C++? In case you are, here is the implementation if you urgently needs it:

```c
#include <X11/Xlib.h>
#include <X11/Xatom.h>
#include <X11/Xresource.h>

double _glfwPlatformGetMonitorDPI(_GLFWmonitor* monitor)
{
    char *resourceString = XResourceManagerString(_glfw.x11.display);
    XrmDatabase db;
    XrmValue value;
    char *type = NULL;
    double dpi = 0.0;

    XrmInitialize(); /* Need to initialize the DB before calling Xrm* functions */

    db = XrmGetStringDatabase(resourceString);

    if (resourceString) {
        printf("Entire DB:\n%s\n", resourceString);
        if (XrmGetResource(db, "Xft.dpi", "String", &type, &value) == True) {
            if (value.addr) {
                dpi = atof(value.addr);
            }
        }
    }

    printf("DPI: %f\n", dpi);
    return dpi;
}
```
It gets the DPI from the `Xft.dpi` as a string and convert to double. The `_glfw.X11.display` can be replaced with a call to `glfwGetX11Display()` to pass the native X11 display.

**Comment by kovidgoyal** [comment] 2017-05-19 18:15
Thanks, currently, I just shell out to xrdb right now in my app, see https://github.com/kovidgoyal/kitty/blob/master/kitty/utils.py#L53

It will just be nice to be able to drop the dependency on xrdb.

**Comment by elmindreda** [comment] 2017-05-23 20:30
@kovidgoyal A function that returns logical DPI or window contents scale (calculated from some base DPI) is planned for 3.3. See #677.

**Comment by elmindreda** [comment] 2017-05-23 20:32
The `per-window-monitor` branch is about returning more accurate physical dimensions on Windows 8.1 and later and isn't (directly) related to this feature.

**Comment by kovidgoyal** [comment] 2017-05-24 01:25
@elmindreda Cool feel free to close this issue in that case.

**Comment by elmindreda** [comment] 2017-06-09 14:28
Closing this as a duplicate of #677. Thank you again for Xft.dpi!

**Closed by elmindreda** 2017-06-09 14:28 UTC
Labels: duplicate, enhancement

**Comment by hanyetinggithub** [comment] 2022-02-23 05:27
> 

Hello, How to get multi monitor's DPI using this method?
