### ISSUE TITLE
Disabling the cursor on Xfce causes keyboard to be grabbed

### ISSUE THREAD

**Issue by dlight** [glfw/glfw#214] opened 2014-01-14 06:13 UTC
I'm sure someone else already noticed this, but I can't find a proper report. (SDL games also have this issue on Linux - it seems to stem from some X weirdness rather than a deliberate attempt to annoy). I'm using GLFW 3.0.4-1 from the Arch Linux repository.

When running fullscreen with GLFW_CURSOR_HIDDEN, I can Alt+TAB normally (good!), but with GLFW_CURSOR_DISABLED the Alt+TAB shortcut is disabled. It seems that's also an issue when you are windowed, but that's not as horribly annoying (IMO).

My understanding is that GLFW_CURSOR_HIDDEN just hides the cursor, so it can still touch the borders of the screen (and then stop movement). When one needs to disable bounds on mouse movement (eg. for moving a camera) GLFW_CURSOR_DISABLED seems to be more adequate. I'm not familiar with GLFW (just evaluating it) so I would be glad to be corrected.

I guess that a workaround would be to use GLFW_CURSOR_HIDDEN and custom code to move the mouse back to the center.

The example wave.c suffer from this issue: it disables the cursor when you grab, so you can rotate freely, but while the cursor is disabled Alt+TAB is impossible. (it's actually worse than that: pressing Alt+TAB while you're grabbing will prevent the cursor to be enabled again after you release the left button, so you need to click again)

Well, the following example isolates the issue, run `./example hidden` or `./example disabled` and press Alt+TAB:

```c
#include <GLFW/glfw3.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

double c_x = 0, c_y = 0;

static void error_callback(int error, const char* description)
{
    fputs(description, stderr);
}

static void cursor_position_callback(GLFWwindow* window, double x, double y)
{
    if (x != c_x || y != c_y)
        printf("Cursor: (%f, %f)\n", x, y);

    c_x = x;
    c_y = y;
}

static void key_callback(GLFWwindow* window, int key, int scancode, int action, int mods)
{
    if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS)
        glfwSetWindowShouldClose(window, GL_TRUE);
}

int main(int argc, char* argv[])
{
    GLFWwindow* window;

    int mode;

    if (argc == 2 && !strcmp(argv[1], "hidden")) {
        mode = GLFW_CURSOR_HIDDEN;
    }
    else if (argc == 2 && !strcmp(argv[1], "disabled")) {
        mode = GLFW_CURSOR_DISABLED;
    }
    else {
        fprintf(stderr, "usage: %s < hidden | disabled >\n", argv[0]);
        exit(EXIT_FAILURE);
    }

    glfwSetErrorCallback(error_callback);

    if (!glfwInit())
        exit(EXIT_FAILURE);

    window = glfwCreateWindow(1366, 768, "Simple example", glfwGetPrimaryMonitor(), NULL);
    if (!window) {
        glfwTerminate();
        exit(EXIT_FAILURE);
    }

    glfwSetInputMode(window, GLFW_CURSOR, mode);

    glfwSetCursorPosCallback(window, cursor_position_callback);
    glfwMakeContextCurrent(window);
    glfwSetKeyCallback(window, key_callback);

    while (!glfwWindowShouldClose(window)) {
        glClear(GL_COLOR_BUFFER_BIT);
        glfwSwapBuffers(window);
        glfwPollEvents();
    }
    glfwDestroyWindow(window);
    glfwTerminate();
    exit(EXIT_SUCCESS);
}
```

**Comment by elmindreda** [comment] 2016-02-21 17:45
This appears to work now on Xfce 4.12 (Ubuntu 15.10).

**Comment by elmindreda** [comment] 2016-02-23 11:11
If anyone can still reproduce me, please let me know. Otherwise I will close this.

**Comment by tombsar** [comment] 2016-02-23 13:29
@elmindreda It still doesn't work for me in icewm (when the cursor is disabled, I cannot alt+tab between windows). It looks as though it is not a bug in glfw, however, so I wouldn't mind if you close this issue.

**Closed** 2016-02-23 17:22 UTC
Labels: bug, X11
