### ISSUE TITLE
ISO C90 forbids mixed declarationsa and code

### ISSUE THREAD

**Issue by tksuoran** [glfw/glfw#1689] opened 2020-05-07 17:45 UTC
When scanning code with clang scan-build, I get these:
```
  380: ../../../subprojects/glfw/src/x11_init.c:228:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  383: ../../../subprojects/glfw/src/x11_init.c:411:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  387: ../../../subprojects/glfw/src/x11_init.c:529:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  390: ../../../subprojects/glfw/src/x11_init.c:558:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  394: ../../../subprojects/glfw/src/x11_init.c:809:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  398: ../../../subprojects/glfw/src/x11_init.c:1049:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  401: ../../../subprojects/glfw/src/x11_init.c:1056:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  414: ../../../subprojects/glfw/src/linux_joystick.c:114:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  418: ../../../subprojects/glfw/src/linux_joystick.c:137:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  421: ../../../subprojects/glfw/src/linux_joystick.c:142:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  424: ../../../subprojects/glfw/src/linux_joystick.c:166:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  427: ../../../subprojects/glfw/src/linux_joystick.c:171:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  430: ../../../subprojects/glfw/src/linux_joystick.c:191:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  433: ../../../subprojects/glfw/src/linux_joystick.c:225:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  437: ../../../subprojects/glfw/src/linux_joystick.c:292:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  440: ../../../subprojects/glfw/src/linux_joystick.c:306:13: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  444: ../../../subprojects/glfw/src/linux_joystick.c:352:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  447: ../../../subprojects/glfw/src/linux_joystick.c:366:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  452: ../../../subprojects/glfw/src/x11_monitor.c:152:13: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  455: ../../../subprojects/glfw/src/x11_monitor.c:174:13: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  459: ../../../subprojects/glfw/src/x11_monitor.c:239:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  462: ../../../subprojects/glfw/src/x11_monitor.c:250:13: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  466: ../../../subprojects/glfw/src/x11_monitor.c:288:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  470: ../../../subprojects/glfw/src/x11_monitor.c:361:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  474: ../../../subprojects/glfw/src/x11_monitor.c:461:13: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  478: ../../../subprojects/glfw/src/x11_monitor.c:571:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  483: ../../../subprojects/glfw/src/x11_window.c:409:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  487: ../../../subprojects/glfw/src/x11_window.c:498:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  491: ../../../subprojects/glfw/src/x11_window.c:624:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  495: ../../../subprojects/glfw/src/x11_window.c:1240:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  498: ../../../subprojects/glfw/src/x11_window.c:1346:17: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  501: ../../../subprojects/glfw/src/x11_window.c:1509:21: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  504: ../../../subprojects/glfw/src/x11_window.c:1542:13: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  507: ../../../subprojects/glfw/src/x11_window.c:1552:17: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  510: ../../../subprojects/glfw/src/x11_window.c:1707:17: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  513: ../../../subprojects/glfw/src/x11_window.c:1837:17: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  517: ../../../subprojects/glfw/src/x11_window.c:1908:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  521: ../../../subprojects/glfw/src/x11_window.c:1982:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  525: ../../../subprojects/glfw/src/x11_window.c:2143:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  529: ../../../subprojects/glfw/src/x11_window.c:2580:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  533: ../../../subprojects/glfw/src/x11_window.c:2900:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  536: ../../../subprojects/glfw/src/x11_window.c:2906:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  539: ../../../subprojects/glfw/src/x11_window.c:2910:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  543: ../../../subprojects/glfw/src/x11_window.c:2965:13: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  547: ../../../subprojects/glfw/src/x11_window.c:3091:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
```

**Comment by tksuoran** [comment] 2020-05-07 17:48
I can make PR if you think this is something that could be merged.

**Comment by aloucks** [comment] 2020-05-07 23:48
I believe `C99` is what's being used for non-windows code:

https://github.com/glfw/glfw/search?q=C99&unscoped_q=C99

**Comment by elmindreda** [comment] 2020-05-13 17:53
The `-Wdeclaration-after-statement` flag shouldn't be applied to those files. I'm not sure why scan-build thinks it should be.

**Comment by elmindreda** [comment] 2020-06-02 16:53
Unable to reproduce this with scan-build and the X11 port and either Clang 8 or 9.

**Comment by elmindreda** [comment] 2022-03-17 19:58
Still unable to reproduce this and there have been nearly two years of build system work in the meantime. Closing this for now. Please re-open this or post a follow-up if there is more information about how to reproduce this.

**Closed by elmindreda** 2022-03-17 19:58 UTC
