### ISSUE TITLE
Aspect ratio incorrectly applied by Openbox

### ISSUE THREAD

**Issue by cdelorme** [glfw/glfw#872] opened 2016-09-29 12:49 UTC
I am running glfw v3.2.1 on debian linux freshly compiled from source.  While the documentation warns that conflicting size limits may pose a problem, I have tried this with 800x600 and 4:3 as well as 1280x720 and 16:9 and both cases yield invalid enforced sizes of 800x599 and 1280x719.

Here is a screenshot:

![glfw aspect ratio invalid size](https://d2xxklvztqk0jd.cloudfront.net/github/issue-images/2016-09-29_083214_492105568-1.png)

Here is the code that produced that screenshot:

```
#include <stdio.h>
#include <GLFW/glfw3.h>

void wresize(GLFWwindow* window, int w, int h)
{
    fprintf(stdout, "Window Resized: %d, %d\n", w, h);
}

void fbresize(GLFWwindow* window, int w, int h)
{
    fprintf(stdout, "Framebuffer Resized: %d, %d\n", w, h);
}

int main(void)
{
    GLFWwindow* window;

    /* Initialize the library */
    if (!glfwInit())
        return -1;

    /* Create a windowed mode window and its OpenGL context */
    window = glfwCreateWindow(1280, 720, "Hello World", NULL, NULL);
    if (!window)
    {
        glfwTerminate();
        return -1;
    }

    /* enforce size restrictions */
    glfwSetWindowSizeLimits(window, 1280, 720, GLFW_DONT_CARE, GLFW_DONT_CARE);
    glfwSetWindowAspectRatio(window, 16, 9);

    /* set callbacks for window and framebuffer resize */
    glfwSetWindowSizeCallback(window, wresize);
    glfwSetFramebufferSizeCallback(window, fbresize);

    /* Make the window's context current */
    glfwMakeContextCurrent(window);

    /* Loop until the user closes the window */
    while (!glfwWindowShouldClose(window))
    {
        /* Render here */
        glClear(GL_COLOR_BUFFER_BIT);

        /* Swap front and back buffers */
        glfwSwapBuffers(window);

        /* Poll for and process events */
        glfwPollEvents();
    }

    glfwTerminate();
    return 0;
}
```

**Removing the size limit and keeping the aspect ratio yields the same invalid initial window size.**  _I am using openbox and a somewhat unusual triple-monitor configuration, but I don't think those would be related specifically._  Is anyone else able to confirm or experience this behavior?

**Comment by tombsar** [comment] 2016-09-29 13:43
I can't reproduce this on Debian Linux using Xfce desktop (with xfwm as window manager). With both size limits and aspect ratio limits enabled, the window and framebuffer both reach the intended 1280x720 resolution.

At a guess, the problem lies somewhere between glfw and Openbox window manager. Are you able to test a different window manager on the same machine?

NB: In testing this I found that size limits don't work at all on my machine with `GLFW_DONT_CARE`s as any of the arguments to `glfwSetWindowSizeLimits`. That's probably a separate issue...

**Comment by elmindreda** [comment] 2016-09-29 15:29
On X11, all code for applying the specified limits to the window is inside the WM. GLFW only sets the associated window properties. Please run the `xprop` utility on the GLFW window and post the output.

**Comment by cdelorme** [comment] 2016-09-29 15:52
@elmindreda, I have never used xprop, but these are pretty obvious:

	WM_NORMAL_HINTS(WM_SIZE_HINTS):
			program specified minimum size: 1280 by 720
			program specified minimum aspect ratio: 16/9
			program specified maximum aspect ratio: 16/9

_I assume that means `glfw` is doing the right thing in spite of the callback getting a size of `1280x719`?_


---

@tombsar, I did not want to make a mess of my host so I tried installing these [desktop environments](https://wiki.debian.org/DesktopEnvironment) inside a VM:

- gnome
- kde
- xfce
- lxde
- mate

With `lxde` (which runs `openbox`) I had invalid dimensions (1280x719), the same results when I ran `openbox` directly (like I do from my host).

I got valid dimensions from `gnome` (1280x720).

I was unable to get `kde`, `xfce`, or `mate` to fprintf; the cpu spiked and system became very unresponsive but no fprintf or any error messages were displayed (could be VM, could be conflicting packages, who knows...)  _The `lxde` environment also spiked CPU but printed dimensions._


---

I encountered the bug from the [go bindings](github.com/go-gl/glfw/), so I am out of my element.  Is this something I should open a ticket for with the openbox folks, and if so what should I add to the ticket?

**Comment by elmindreda** [comment] 2016-10-10 13:53
@cdelorme Yes, it looks like GLFW and the bindings are passing the data along correctly. Please forward the bug to Openbox.

**Comment by cdelorme** [comment] 2016-10-10 14:18
Just a quick update; I [opened a bug report with openbox](https://bugzilla.icculus.org/show_bug.cgi?id=6450).

**Comment by elmindreda** [comment] 2017-03-27 18:02
This seems to have been accepted and assigned at their end. Closing this.

**Closed by elmindreda** 2017-03-27 18:02 UTC
Labels: bug, external, waiting, X11
