### ISSUE TITLE
Joystick polling is slower than expected

### ISSUE THREAD

**Issue by theagentd** [glfw/glfw#602] opened 2015-09-09 14:31 UTC
We do input polling and game state updating at a fairly high rate in our game, at 250Hz. Joystick polling seems to be significantly slower than expected, which causes problems for us.

With no joysticks connected, calling glfwJoystickPresent() for all 16 joystick slots takes 0.116ms on average to complete, totaling 29ms per 1000 second.

Calling glfwGetJoystickAxes() and glfwGetJoystickButtons() for each of the 16 joysticks (without having any connected though) takes an average of 0.189 ms, totaling 47.25ms per second. This is a significant chunk of our total frame-time as we have a budget around 2-3 ms for each update.

This is further incentive to add callback support and/or add threading support to joystick polling. Threading support is in my opinion preferred and should also be easier to implement.

**Comment by elmindreda** [comment] 2015-09-09 15:19
Why are you polling for buttons and axes on joysticks you have already determined are not present?

**Comment by theagentd** [comment] 2015-09-09 17:27
We will not have a limit on the number of players that can play the game simultaneously, so we may actually have 16 controllers in use at the same time. It is 5-10% of our time budget that could be off-loaded to a different thread or be optimized.

**Comment by elmindreda** [comment] 2015-09-16 18:29
What I meant was, it sounds like you're making all three calls on all slots, regardless of the results of `glfwJoystickPresent`.

None of this is meant to let me off the hook, of course. Those calls are unacceptably slow. The real solution to this is #232.

**Comment by theagentd** [comment] 2015-09-17 09:41
No, I'm only calling glfwGetJoystickAxes() and glfwGetJoystickButtons() in the second test where it takes 47.25ms/second. Xinput support would solve a few other problems as well for us, like the Xbox trigger buttons being bound to an axis with the current joystick system.

**Comment by elmindreda** [comment] 2015-09-17 11:46
I'll close this as a duplicate of #232 then.

**Closed by elmindreda** 2015-09-17 11:46 UTC
Labels: bug, Windows
