### ISSUE TITLE
Vsync doesn't work on macOS 12.0 (Monterey)

### ISSUE THREAD

**Issue by kivutar** [glfw/glfw#1990] opened 2021-11-13 04:33 UTC
Vsync stopped working in glfw on Monterey.

This issue is also affecting other technologies like SDL: https://github.com/libsdl-org/SDL/issues/4918

This is a possible fix for SDL: https://github.com/libsdl-org/SDL/commit/13869f194c5b975aefac6517e58998f11108d722

The same issue is affecting games like Minecraft, and maybe more games: https://www.reddit.com/r/macgaming/comments/qh26yg/dont_upgrade_to_monterey_vsync_broken_in_most/

It might be related to https://github.com/glfw/glfw/issues/1337

go-gl/glfw is also affected

**Comment by dmitshur** [comment] 2021-11-13 23:59
What I'm observing with macOS 12 and GLFW 3.3.4 (via go-gl/glfw) is that vsync does have an effect, but it synchronizes to the wrong refresh rate.

In my case specifically, I have a 60 hz display, but my OpenGL app with vsync runs at exactly 120 FPS. (If I turn off vsync, then it runs at 600-800 FPS.) It happens both on the built-in 60 hz display, as well with an external 60 hz display.

It seems quite likely connected to the recently released MacBook Pros with displays that go up to 120 hz maximum rather than the usual 60 hz.

**Comment by sfuller** [comment] 2021-11-20 20:54
I think glfwSwapInterval(1) is working as intended, waiting one screen update before swapping buffers. It just happens that a screen update on the new MacBook is faster, occuring at 120 hz instead of 60 hz.
It sounds like a new glfw api to query the system's screen update time would be helpful so that the correct swap interval can be calculated.

**Comment by kivutar** [comment] 2021-11-21 08:11
I tried setting my SwapInterval to 2, but it's still not achieving good vsync like before. Tested on my 60Hz macbook pro from 2017.

**Comment by elmindreda** [comment] 2021-11-24 22:42
Thank you for reporting this! Hopefully this will be fixed by Apple, like it eventually was with macOS 10.14. Like SDL we too switched over to using display link that time but that introduced issues on other versions of macOS.

In the meantime I'm open to alternate or temporary fixes or workarounds, as long as they don't impact earlier versions.

**Comment by fabioarnold** [comment] 2021-11-25 10:05
> I think glfwSwapInterval(1) is working as intended, waiting one screen update before swapping buffers. It just happens that a screen update on the new MacBook is faster, occuring at 120 hz instead of 60 hz.

It's not working as intended. I have both an M1 MacBook Air with a 60 Hz display and a 14" M1 MacBook Pro from 2021 with a 120 Hz display. The problem surfaced after the update from macOS 11 to macOS 12. On the Air my app now refreshes at 120 Hz. On the new Pro my app refreshes at 240 Hz. So, it's simply doubled.

**Comment by hajimehoshi** [comment] 2021-11-26 18:00
I found Metal (using `GLFW_NO_API` and rendering with `CAMetalLayer` and so on) worked well with vsync. I don't find a good solution for OpenGL so far.

**Comment by GameParrot** [comment] 2021-12-13 22:35
It seems to be fixed in Monterey 12.1!

**Comment by dmitshur** [comment] 2021-12-14 02:59
I can confirm @GameParrot's finding.

I've retested an OpenGL application mentioned in https://github.com/glfw/glfw/issues/1990#issuecomment-968177486 right before, while on macOS 12.0.1 (21A559), and immediately after updating to macOS 12.1 (21C52). Without changing anything else, the issue reproduced on 12.0.1 and got fixed in 12.1: vsync results in the app correctly running at 60 fps instead of 120 fps on the 60 hz display of the MBA.

**Comment by kivutar** [comment] 2021-12-14 07:46
I confirm the issue is fixed by the update for me too.

**Comment by ptxmac** [comment] 2022-09-18 22:06
It seems this issue has reappeared on Mac OS 13 (currently in beta)

**Comment by led93** [comment] 2022-11-06 19:32
@ptxmac is it fair to assume it will be fixed by Apple again at some point?

**Comment by ptxmac** [comment] 2022-11-06 19:37
I doubt it. Macos venture is released and the bus still exists. 

It's also present in the next beta

**Comment by ptxmac** [comment] 2022-11-07 09:30
Small update, I also see this issue with SDL on macos

**Comment by bendeguzbagi** [comment] 2023-01-09 19:49
Issue still exists in 13.1 :/

**Closed** 2023-01-09 22:09 UTC
Labels: bug, macOS, verified, external, OpenGL

**Comment by elmindreda** [comment] 2023-01-09 22:18
Please come to #2249 for the macOS 13 edition of vsync being broken and we can let this one rest.
