### ISSUE TITLE
Occluded window giving 100% CPU usage despite v-sync

### ISSUE THREAD

**Issue by Andos** [glfw/glfw#751] opened 2016-04-27 07:27 UTC
OSX does occlusion checking on windows and completely ignores Vsync on those (either occluded behind other windows, minimized or on a different OSX "Desktop".
This leaves them running at 100% CPU because the vsync time is reduced to a virtual 0ms.

Instead of having to manually listen to the Cocoa **NSWindowDidChangeOcclusionStateNotification** and implement a manual frame-rate limiter it would be nice if GLFW handled this to some degree - maybe emulating the last known frame rate until the window becomes visible again - or maybe even 
throttling the framerate down to some customizable setting for occluded windows to save energy.

**Comment by elmindreda** [comment] 2016-04-27 10:31
This is a duplicate of #680.

**Closed** 2017-03-23 19:06 UTC
Labels: bug, duplicate, macOS
