### ISSUE TITLE
Crashed on 10.12 when pressing Cmd+C

### ISSUE THREAD

**Issue by woc2006** [glfw/glfw#911] opened 2016-12-03 08:32 UTC
Crash log:

2016-12-03 16:25:58.903821 Test[85641:404480] -[GLFWContentView copy:]: unrecognized selector sent to instance 0x610000140420
2016-12-03 16:25:58.907716 Test[85641:404480] [General] An uncaught exception was raised

2016-12-03 16:25:58.907760 Test[85641:404480] [General] -[GLFWContentView copy:]: unrecognized selector sent to instance 0x610000140420
2016-12-03 16:25:58.908190 Test[85641:404480] [General] (
	0   CoreFoundation                      0x00007fff982706fb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffacc14a2a objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff982f0cc4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff981e3f03 ___forwarding___ + 1059
	4   CoreFoundation                      0x00007fff981e3a58 _CF_forwarding_prep_0 + 120
	5   libsystem_trace.dylib               0x00007fffad723c41 _os_activity_initiate + 61
	6   AppKit                              0x00007fff964f2770 -[NSApplication(NSResponder) sendAction:to:from:] + 456
	7   Test                              0x0000000100d2d4f5 -[NSTextField(copypaste) performKeyEquivalent:] + 405
	8   AppKit                              0x00007fff95fc7974 -[NSView _performKeyEquivalent:conditionally:] + 227
	9   AppKit                              0x00007fff95fc7ba1 -[NSControl _performKeyEquivalent:conditionally:] + 136
	10  AppKit                              0x00007fff95fc7a72 -[NSView performKeyEquivalent:] + 234
	11  AppKit                              0x00007fff95fc7974 -[NSView _performKeyEquivalent:conditionally:] + 227
	12  AppKit                              0x00007fff95fc7a72 -[NSView performKeyEquivalent:] + 234
	13  AppKit                              0x00007fff95fc7974 -[NSView _performKeyEquivalent:conditionally:] + 227
	14  AppKit                              0x00007fff95fc7a72 -[NSView performKeyEquivalent:] + 234
	15  AppKit                              0x00007fff95fc7974 -[NSView _performKeyEquivalent:conditionally:] + 227
	16  AppKit                              0x00007fff96614342 -[NSWindow _commonPerformKeyEquivalent:conditionally:] + 79
	17  AppKit                              0x00007fff964f118c routeKeyEquivalent + 572
	18  AppKit                              0x00007fff964eefad -[NSApplication(NSEvent) sendEvent:] + 3377
	19  Test                              0x0000000100bcd182 -[GLFWApplication sendEvent:] + 98
	20  Test                              0x0000000100bced1d _glfwPlatformPollEvents + 109
	21  Test                              0x0000000100b78691 _ZN7cocos2d6GLView10pollEventsEv + 17
	22  Test                              0x0000000100bb8224 _ZN7cocos2d11Application3runEv + 148
	23  Test                              0x00000001000a8fab main + 1195
	24  libdyld.dylib                       0x00007fffad4f1255 start + 1
	25  ???                                 0x0000000000000003 0x0 + 3
)
2016-12-03 16:25:58.908509 Test[85641:404480] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[GLFWContentView copy:]: unrecognized selector sent to instance 0x610000140420'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff982706fb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffacc14a2a objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff982f0cc4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff981e3f03 ___forwarding___ + 1059
	4   CoreFoundation                      0x00007fff981e3a58 _CF_forwarding_prep_0 + 120
	5   libsystem_trace.dylib               0x00007fffad723c41 _os_activity_initiate + 61
	6   AppKit                              0x00007fff964f2770 -[NSApplication(NSResponder) sendAction:to:from:] + 456
	7   Test                              0x0000000100d2d4f5 -[NSTextField(copypaste) performKeyEquivalent:] + 405
	8   AppKit                              0x00007fff95fc7974 -[NSView _performKeyEquivalent:conditionally:] + 227
	9   AppKit                              0x00007fff95fc7ba1 -[NSControl _performKeyEquivalent:conditionally:] + 136
	10  AppKit                              0x00007fff95fc7a72 -[NSView performKeyEquivalent:] + 234
	11  AppKit                              0x00007fff95fc7974 -[NSView _performKeyEquivalent:conditionally:] + 227
	12  AppKit                              0x00007fff95fc7a72 -[NSView performKeyEquivalent:] + 234
	13  AppKit                              0x00007fff95fc7974 -[NSView _performKeyEquivalent:conditionally:] + 227
	14  AppKit                              0x00007fff95fc7a72 -[NSView performKeyEquivalent:] + 234
	15  AppKit                              0x00007fff95fc7974 -[NSView _performKeyEquivalent:conditionally:] + 227
	16  AppKit                              0x00007fff96614342 -[NSWindow _commonPerformKeyEquivalent:conditionally:] + 79
	17  AppKit                              0x00007fff964f118c routeKeyEquivalent + 572
	18  AppKit                              0x00007fff964eefad -[NSApplication(NSEvent) sendEvent:] + 3377
	19  Test                              0x0000000100bcd182 -[GLFWApplication sendEvent:] + 98
	20  Test                              0x0000000100bced1d _glfwPlatformPollEvents + 109
	21  Test                              0x0000000100b78691 _ZN7cocos2d6GLView10pollEventsEv + 17
	22  Test                              0x0000000100bb8224 _ZN7cocos2d11Application3runEv + 148
	23  Test                              0x00000001000a8fab main + 1195
	24  libdyld.dylib                       0x00007fffad4f1255 start + 1
	25  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by elmindreda** [comment] 2016-12-03 18:10
The menu bar created by GLFW does not contain an item for this selector.

**Comment by elmindreda** [comment] 2016-12-03 18:12
Do you need to perform any other steps than Cmd+C to reproduce this? What keyboard input language do you have and are you using an IME? Does the application menu bar contain a Copy item?

**Comment by woc2006** [comment] 2016-12-09 13:13
1. Do you need to perform any other steps than Cmd+C to reproduce this?
A: No, just Cmd+C

2. What keyboard input language do you have and are you using an IME?
A: Default IME on 10.12, English keyboard

3. Does the application menu bar contain a Copy item?
A: No, I haven't customized menu bar.

**Comment by lenrico** [comment] 2016-12-13 21:25
the same here just with pressed ALT key instead, it seems that GLFW can't handle mac os x (maybe also sierra or older versions) specific alternate (or better known as mode keys).

simple to reproduce...

`
#include <iostream>
#include "lib/glfw-3.2.1/include/GLFW/glfw3.h"
#include <OpenGL/gl.h>

enum KEY {
	A	= GLFW_KEY_A,
	B	= GLFW_KEY_B,
	C	= GLFW_KEY_C,
	SP	= GLFW_KEY_SPACE
};

GLFWwindow *win = nullptr;

bool base_init() {
	glfwSetErrorCallback( [](int n, const char* m){ std::cout << "Error[" << n << "] : "<< m << std::endl; } );
	glfwInit();
	win = glfwCreateWindow( 300, 300, "test1", nullptr, nullptr );

	if( win ) {
		glfwSetKeyCallback( win, [](GLFWwindow *window, int key, int code, int action, int mods) {
			if( action == GLFW_PRESS ) {
				switch ( key ) {
					case KEY::A: { std::cout << "pressed A key : " << mods << std::endl; } break;
					case KEY::B: { std::cout << "pressed B key : " << mods << std::endl; } break;
					case KEY::C: { std::cout << "pressed C key : " << mods << std::endl; } break;
					case KEY::SP: { std::cout << "pressed SPACE key : " << mods << std::endl; } break;
					default: { std::cout << "uncatched key '" << glfwGetKeyName( key, code ) << "' pressed" << std::endl; };
				}
			}
		});

		glfwMakeContextCurrent( win );

		return true;
	}

	return false;
}

int main() {
	if( base_init() ) {
		while( !glfwWindowShouldClose( win ) ) {
			/* Render here */
			glClear( GL_COLOR_BUFFER_BIT );

			/* Swap front and back buffers */
			glfwSwapBuffers( win );

			/* Poll for and process events */
			glfwPollEvents();
		}
	} else {
		std::cerr <<  "can't create window or something else" << std::endl;
	}

	glfwTerminate();
	return 0;
}
`

any ideas?

**Comment by lenrico** [comment] 2016-12-13 21:27
compliled under mac os x el capitan 10.11.6 with clang...
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

<img width="953" alt="screenshot_20161213_222658" src="https://cloud.githubusercontent.com/assets/4271131/21159927/52a2a88a-c183-11e6-9699-cbf16f666f01.png">

**Comment by lenrico** [comment] 2016-12-13 21:32
my keyboard language is german.

**Comment by elmindreda** [comment] 2016-12-14 14:52
@woc2006 What does the menu bar look like in your program?

**Comment by elmindreda** [comment] 2016-12-14 14:54
@lenrico Sorry, what is the issue you are having?

**Comment by lenrico** [comment] 2016-12-16 06:53
@elmindreda my keyboard looks like this (http://images.google.de/imgres?imgurl=https%3A%2F%2Feduardoconto.files.wordpress.com%2F2013%2F10%2F20131002_103510.jpg&imgrefurl=https%3A%2F%2Feduardoconto.wordpress.com%2F2013%2F10%2F02%2Fmacbook-pro-us-international-keyboard-layout-for-windows%2F&h=1266&w=3250&tbnid=vD-oIo7l8ORrHM%3A&vet=1&docid=-i1sXUEvi9RdiM&ei=b45TWKLZN8TWUZHskJgC&tbm=isch&iact=rc&uact=3&dur=2585&page=0&start=0&ndsp=26&ved=0ahUKEwjizKzBj_jQAhVEaxQKHRE2BCMQMwg4KBYwFg&bih=949&biw=1680) 

if i press the ALT key with the example app above, then i faced with a program crash, but why...?

it seems that glfwKeyName can't handle unknown keys.

**Comment by elmindreda** [comment] 2016-12-16 11:36
@lenrico [The documentation](http://www.glfw.org/docs/latest/group__input.html#ga237a182e5ec0b21ce64543f3b5e7e2be) describes what keys `glfwGetKeyName` will return the name of.

**Comment by woc2006** [comment] 2016-12-16 11:45
@elmindreda Here's my menu bar.
<img width="208" alt="qq20161216-0 2x" src="https://cloud.githubusercontent.com/assets/1716430/21261741/2f7534c6-c3c8-11e6-944b-a4dbfaa49f21.png">

**Comment by jaredjones** [comment] 2017-01-09 06:38
@elmindreda 
This is a non-issue, the error lies with the code being used.
std::cout << "uncatched key '" << glfwGetKeyName( key, code ) << "' pressed" << std::endl;

Since glfwGetKeyName() returns NULL for key names that it doesn't know, the operator overload of "<<" referenced in std::basicostream on OS X crashes because you cannot concatenate a NULL character in C++ in the Clang representation of the C++ standard library.

**Comment by lenrico** [comment] 2017-01-09 18:41
@jaredjones 

> Since glfwGetKeyName() returns NULL for key names that it doesn't know, the operator overload of "<<" referenced in std::basicostream on OS X crashes because you cannot concatenate a NULL character in C++ in the Clang representation of the C++ standard library.

agree with that, which is a normal behavior.

then i should first check if 'int mods' is pressed.

**Comment by elmindreda** [comment] 2017-01-10 16:51
@jaredjones Agreed. I'm not sure about the original issue by @woc2006, however.

**Comment by tombsar** [comment] 2019-05-10 15:47
@woc2006 Can you please report if this is still an issue for you? A lot has changed in both glfw and macOS since this issue was created.

**Comment by woc2006** [comment] 2019-05-12 14:55
> @woc2006 Can you please report if this is still an issue for you? A lot has changed in both glfw and macOS since this issue was created.

It's fixed in the latest code. Good job!

**Comment by lenrico** [comment] 2019-05-13 15:12
> > @woc2006 Can you please report if this is still an issue for you? A lot has changed in both glfw and macOS since this issue was created.
> 
> It's fixed in the latest code. Good job!

it's fixed now, thanks to all.

**Closed** 2019-05-14 14:39 UTC
Labels: bug, cannot reproduce, macOS
