### ISSUE TITLE
Controller axes are flipped

### ISSUE THREAD

**Issue by BryceMehring** [glfw/glfw#201] opened 2014-01-01 20:51 UTC
I'm using a Xbox 360 controller which I've tested on both Windows and Linux. On Windows while using the right stick, the y axis is the 4th axis while the x axis is the 5th. On Linux, it is flipped. The right sticks y axis is the 5th axis and the x axis is the 4th.

**Comment by elmindreda** [comment] 2015-01-19 01:03
Closing this as a special case duplicate of #341.

**Closed by elmindreda** 2015-01-19 01:03 UTC
Labels: bug, duplicate, X11
