### ISSUE TITLE
Request basic support for Microsoft GDI software OpenGL

### ISSUE THREAD

**Issue by qianyizh** [glfw/glfw#862] opened 2016-09-17 22:29 UTC
In current GLFW (3.3, 433db8f9f9e3ef7a1cc001d4888d92f8ed543630), GLFW context cannot be created on Microsoft Remote Desktop. This annoys me since I am developing a library that is supposed to run a lot in remote environment.

I read the GLFW document and noticed this:
```
Windows: Window creation will fail if the Microsoft GDI software OpenGL implementation is the only one available.
```
I am asking if supporting Microsoft GDI software OpenGL can be a future feature.

I understand that Microsoft GDI has very limited OpenGL support. But this is like the case of virtualization. I have used GLFW heavily in VirtualBox (which supports up to OpenGL 2.0) and it worked okay to a certain extent.

The requested feature is also mentioned in #45 
```
However, a window hint that allows software renderers to be selected is planned for 3.x. It's going to default to off.
```
I am wondering if the hint is still on the road map, :)

**Comment by qianyizh** [comment] 2016-09-17 22:35
Just to complete the request.

The version of GLFW is 3.3 (433db8f9f9e3ef7a1cc001d4888d92f8ed543630).

When I run glfwinfo on my windows machines (I tried two host machines, one has Windows 10, one has Windows 8.), it reports:
```
> ./glfwinfo.exe                                                                     
GLFW header version: 3.3.0                                                           
GLFW library version: 3.3.0                                                          
GLFW library version string: "3.3.0 Win32 WGL EGL VisualC"                           
OpenGL context version string: "4.5.0 NVIDIA 353.82"                                 
OpenGL context version parsed by GLFW: 4.5.0                                         
OpenGL context flags (0x00000000):                                                   
OpenGL context flags parsed by GLFW:                                                 
OpenGL profile mask (0x00000000): unknown                                            
OpenGL profile mask parsed by GLFW: compat                                           
OpenGL robustness strategy (0x00008261): none                                        
OpenGL robustness strategy parsed by GLFW: none                                      
OpenGL context renderer string: "GeForce GTX 970/PCIe/SSE2"                          
OpenGL context vendor string: "NVIDIA Corporation"                                   
OpenGL context shading language version: "4.50 NVIDIA"                               
OpenGL framebuffer:                                                                  
 red: 8 green: 8 blue: 8 alpha: 8 depth: 24 stencil: 8                               
 samples: 0 sample buffers: 0                                                        
 accum red: 16 accum green: 16 accum blue: 16 accum alpha: 16 aux buffers: 4         
Vulkan loader: missing                                                               
```

In remote desktop (Microsoft Remote Desktop OS X version 8.0.34, or native Remote Desktop Connection on another Windows machine) it reports:
```
> ./glfwinfo.exe
GLFW header version: 3.3.0
GLFW library version: 3.3.0
GLFW library version string: "3.3.0 Win32 WGL EGL VisualC"
Error: WGL: The driver does not appear to support OpenGL
```

**Comment by elmindreda** [comment] 2016-09-27 23:21
You're in luck! This is a duplicate of #589, which is already scheduled for the next release.

**Comment by elmindreda** [comment] 2016-09-28 12:20
I'm closing this as a duplicate of #589.

**Closed by elmindreda** 2016-09-28 12:20 UTC
Labels: duplicate, enhancement, Windows
