### ISSUE TITLE
Program Gets Segmentation Fault On Resize

### ISSUE THREAD

**Issue by jeffro256** [glfw/glfw#596] opened 2015-09-07 01:13 UTC
I have created a window with the code copied and pasted from <a href='http://postimg.org/image/h5rx7v9nt/full/' target='_blank'><img src='http://s28.postimg.org/fqqcj58kt/Screen_Shot_2015_09_06_at_7_44_50_PM.png' border='0' alt="Screen Shot 2015 09 06 at 7 44 50 PM" /></a><br /><a target='_blank' href='http://postimage.org/'>upload pics</a><br /><br />
I linked using the command:
```bash
gcc filename.c -o filename -I /opt/local/include/ -L /opt/local/lib -l glfw
```
This gives me a black, blank window: 
<a href='http://postimg.org/image/woeueq5v5/full/' target='_blank'><img src='http://s16.postimg.org/mecffhfzp/Screen_Shot_2015_09_06_at_7_53_05_PM.png' border='0' alt="Screen Shot 2015 09 06 at 7 53 05 PM" /></a><br /><a target='_blank' href='http://postimage.org/'>img upload</a><br /><br />
Now this is a nice and lovely black window, but something dark happens if I try to squish the window too thin top to bottom:
<img src="http://i.giphy.com/3o85xIljBk6r4jk20E.gif"></img>
My program crashes and gives me a ```segmentation fault: 11```. I don't know why this happens but I would really like this problem to be fixed, it is quite annoying. I am using Using Mac OS 10.10.5. My GLFW Version is 3.1.1, as far as I know.

**Comment by shurcooL** [comment] 2015-09-07 01:27
I can reproduce this with `events` test program.

**Comment by elmindreda** [comment] 2015-09-07 01:54
Duplicate of #443.

**Closed by elmindreda** 2015-09-07 01:54 UTC
Labels: duplicate
