### ISSUE TITLE
make use of gamepad and joystick optional

### ISSUE THREAD

**Issue by iamAdrianIusca** [glfw/glfw#1646] opened 2020-02-13 09:55 UTC
Hi @elmindreda , is there a chance to have some way to "disable" the code for the joystick and gamepad if I don't have applications that make use of them? I made some investigations and I am sure that it will be an improvement at least at the startup of the app. 

We can define some cmake option for the gamepad and joystick which is enable by default and just disabled when you know for sure that you will use just mouse and keyboard. This option can set some macro and the code will not be compiled.

I can write the code, if you are open to do such a scenario.

**Comment by ForeverZer0** [comment] 2020-02-23 14:57
Why not just fork the project and remove it for your project?

Like literally every single other feature in the library, "don't use it if you don't need it" seems like the simple answer. There are no shortage of features that might go unused by different projects, making a conditional macro for each one seems like overkill. Gamepad support for a library whose primary use is games seems like among the least of these.

> I made some investigations and I am sure that it will be an improvement at least at the startup of the app
Would be curious to see your tests and results to see the impact on different systems.

**Comment by iamAdrianIusca** [comment] 2020-02-23 21:05
Hi @ForeverZer0 thanks for your feedback, but this is a public repository and opened to receive questions, so your "Like literally every single other feature in the library, "don't use it if you don't need it" seems like the simple answer." is not a good thing to say.

**Comment by ForeverZer0** [comment] 2020-02-23 21:50
@iamAdrianIusca I had no intention to come off as dismissive of your question or insulting, please don't interpret as such, was only offering feedback on the matter in plain language. I am unclear why you see that as "not a good thing to say" simply over not being in agreement over your proposed issue. GitHub issues are an open discussion format for others to participate in.

**Comment by aloucks** [comment] 2020-02-23 22:04
> I made some investigations and I am sure that it will be an improvement at least at the startup of the app.

Out of curiosity, what is "it" in this sentence? What will be improved by making joystick/gamepad support compile options?

**Comment by iamAdrianIusca** [comment] 2020-02-23 22:39
@aloucks I think the first improvement for making gamepad/joystick optional is not using DirectInput anymore as Microsoft recommands just using windows message loop for keyboard and mouse input.

**Comment by iamAdrianIusca** [comment] 2020-02-23 22:49
@ForeverZer0 I know this library is used mostly for games, but most of the games are using just mouse and keyboard.

**Comment by aloucks** [comment] 2020-02-23 23:58
> @aloucks I think the first improvement for making gamepad/joystick optional is not using DirectInput anymore (just when you disable this feature) as Microsoft recommands just using windows message loop for keyboard and mouse input.

Again, what is the actual benefit of this?

**Comment by iamAdrianIusca** [comment] 2020-02-24 00:13
@aloucks less function calls when you create the window

**Comment by ForeverZer0** [comment] 2020-02-24 00:22
> @ForeverZer0 I know this library is used mostly for games, but most of the games are using just mouse and keyboard.

What evidence do you have to support such a statement? Of the 30-40 games on my HDD right now, 100% of them support gamepad input.

**Comment by aloucks** [comment] 2020-02-24 00:33
> @aloucks less function calls when you create the window

What do you  mean? There aren't any required functions related to joystick support when creating a window. Here is a basic example:

```C
#include "GLFW/glfw3.h"

void key_callback(GLFWwindow* window, int key, int scancode, int action, int mods) {
    if (key == GLFW_KEY_ESCAPE) {
        glfwSetWindowShouldClose(window, GLFW_TRUE);
    }
}

int main() {
    glfwInit();
    GLFWwindow* window = glfwCreateWindow(800, 600, "GLFW Window", NULL, NULL);
    glfwSetKeyCallback(window, key_callback);
    while (!glfwWindowShouldClose(window)) {
        glfwWaitEvents(); // or glfwPollEvents();
        renderFrameHere();
    }
    glfwTerminate();
}
```

**Comment by iamAdrianIusca** [comment] 2020-02-24 00:54
@aloucks I meant less calls "under the hood".

**Comment by iamAdrianIusca** [comment] 2020-02-24 00:55
@ForeverZer0 Ok and all of them are made with glfw?

**Comment by aloucks** [comment] 2020-02-24 00:58
> @aloucks I meant less calls "under the hood".

I still don't understanding how you're quantifying this as an "improvement". What actual benefit does the user gain by those calls "under the hood" being removed?

**Comment by iamAdrianIusca** [comment] 2020-02-24 01:01
@aloucks just look into the win32_joystick.c file of this project, just think that all that code it will not be compiled in your project.

**Comment by iamAdrianIusca** [comment] 2020-02-24 01:36
Anyway, my point is to create a way to disable the joystick and gamepad if you have a small project and you don't want it. Assimp library for example have a CMake variable which can be set if you do not want to have the export functionalities in your project.

**Comment by ghuser404** [comment] 2020-02-24 05:02
>I made some investigations and I am sure that it will be an improvement at least at the startup of the app

By _"investigations"_ you mean you just inspected GLFW source code or did you actually benchmark it? Considering you say _"I am sure"_, I'll assume the former.

What kind of improvements are we actually talking here, 1ms? I may be wrong, but it's probably even less than that, that's why no one understands why such option is needed. Maybe if you could present actual result, then people would get persuaded that this is actually a valid request.

**Comment by iamAdrianIusca** [comment] 2020-02-24 11:49
Ok then, I will come back with some numbers.

**Comment by ronchaine** [comment] 2020-02-28 13:20
> > I made some investigations and I am sure that it will be an improvement at least at the startup of the app
> 
> By _"investigations"_ you mean you just inspected GLFW source code or did you actually benchmark it? Considering you say _"I am sure"_, I'll assume the former.
> 
> What kind of improvements are we actually talking here, 1ms? I may be wrong, but it's probably even less than that, that's why no one understands why such option is needed. Maybe if you could present actual result, then people would get persuaded that this is actually a valid request.

There is around 1-2 second delay on Linux when initialising joystick code.  I don't know if it manifests on every system, but this is not the first time this gets mentioned.  The delay's been there for ages., and it goes away if you comment out the joystick init code.

```
#include <GLFW/glfw3.h>
#include <chrono>
#include <iostream>

int main()
{
    auto start = std::chrono::steady_clock::now();
    glfwInit();
    glfwTerminate();
    auto end = std::chrono::steady_clock::now();

    std::cout << "took " << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << "ms\n";
}
```

With joystick code intact, with Intel 8660U (Battery or AC doesn't affect the test):
```
[ronchaine@mellori (0) ~/Source/glfw-perf]$ ./a.out
took 1024ms
[ronchaine@mellori (0) ~/Source/glfw-perf]$ ./a.out
took 1058ms
[ronchaine@mellori (0) ~/Source/glfw-perf]$ ./a.out
took 1112ms
[ronchaine@mellori (0) ~/Source/glfw-perf]$ ./a.out
took 1046ms
```

Patch:
```
@@ -268,6 +268,7 @@ static int compareJoysticks(const void* fp, const void* sp)
 //
 GLFWbool _glfwInitJoysticksLinux(void)
 {
+    return;
     const char* dirname = "/dev/input";
 
     _glfw.linjs.inotify = inotify_init1(IN_NONBLOCK | IN_CLOEXEC);
```

```
[ronchaine@mellori (0) ~/Source/glfw-perf]$ ./a.out
took 1ms
[ronchaine@mellori (0) ~/Source/glfw-perf]$ ./a.out
took 0ms
[ronchaine@mellori (0) ~/Source/glfw-perf]$ ./a.out
took 2ms
[ronchaine@mellori (0) ~/Source/glfw-perf]$ ./a.out
took 2ms
```

**Comment by iamAdrianIusca** [comment] 2020-02-28 15:08
Thanks @ronchaine I will come back with the numbers on windows.

**Comment by ghuser404** [comment] 2020-02-29 04:29
I tried this on Windows, it takes around 150ms, not as bad as 1s.

**Comment by aloucks** [comment] 2020-02-29 05:05
Odd, I can't reproduce those timings. This is on Ubuntu 19.04.

```
$ cat main.c
#include <GLFW/glfw3.h>
 
int main()
{
    glfwInit();
    glfwTerminate();
}
 
$ cc main.c -I glfw/include/ -L glfw/src/ -lglfw3 -lrt -lm -ldl -lpthread
$ time ./a.out
 
real    0m0.015s
user    0m0.006s
sys 0m0.006s
```

**Comment by ghuser404** [comment] 2020-02-29 06:19
Maybe something changed in GLFW code.
@ronchaine @aloucks What versions do you have?

**Comment by ronchaine** [comment] 2020-02-29 07:03
I use current master branch of GLFW, but this has been present from at least 2018.  e.g. https://github.com/kovidgoyal/kitty/issues/830

**Comment by ghuser404** [comment] 2020-02-29 07:28
What could be the difference with your and @aloucks setup?

**Comment by ForeverZer0** [comment] 2020-02-29 15:29
On Arch Linux with X11, GLFW 3.3.2.1

Using the minimal example:
```c
#include <GLFW/glfw3.h>
 
int main()
{
    glfwInit();
    glfwTerminate();
}
```

```
$ cc main.c -I glfw/include/ -L glfw/src/ -lglfw -lrt -lm -ldl -lpthread
$ time ./a.out

real    0m0.046s
user    0m0.010s
sys     0m0.014s
```

**Comment by aloucks** [comment] 2020-02-29 15:36
@ghuser404 I was using a fresh clone of glfw master.

**Comment by tombsar** [comment] 2020-02-29 15:51
The actual init time will depend on how many devices your system thinks it has connected, and which devices they are (depending on how many properties, axes, etc they expose).

**Comment by ForeverZer0** [comment] 2020-02-29 16:14
@tombsar With a single generic X-Box pad (wired) (and wireless mouse dongle if that matters):

```
real    0m0.082s
user    0m0.012s
sys     0m0.011s
```

**Comment by ronchaine** [comment] 2020-02-29 16:19
I am using currently using Arch with Thinkpad X1 Tablet Gen 3 with zero controllers connected.  There are 32 event devices in /dev/input though.

**Comment by tombsar** [comment] 2020-02-29 18:36
@ForeverZer0 I doubt that it being in the database or not has any significant impact on the speed. Might be worth investigating if anyone has the inclination, but I'd be willing to bet most time is spent just enumerating and querying the devices.

Personally, I sympathise with this issue. An extra second of app startup time for no benefit (if you aren't intending to use joystick input) feels unacceptable. And it would be a very small code change to allow a dev to switch it off.

However, every compile-time switch we introduce upstream is another thing to document and test in perpetuity (e.g. if future code changes implicitly rely on certain joystick state to have been initialised, etc. everything should be tested both with and without joystick code enabled). We also do not want to end up in a state where somebody could unknowingly have a glfw .dll or .so on their system with joystick code compiled out (maybe a Linux distro or language port issues a misconfigured package), and an app developer being utterly confused when their programs work in one environment but not another. Then we need to start thinking about whether certain joystick calls should error out, or adding a function to test at runtime whether support has been compiled in etc etc. Do-able, but not zero cost.

Perhaps a runtime init hint would be a good compromise? Then support is available by default everywhere, but any app can choose to skip the init step to save on startup time.

I'm not decided, but leaning towards encouraging developers who care about startup time and don't care about joysticks to hack the source themselves, and making no change upstream.

**Comment by ForeverZer0** [comment] 2020-02-29 21:37
@tombsar I agree if any action were to be taken, an init hint seems like it would be a good middle-ground, where the possibility is there to disable if desired, but it is fully controlled by the consumer of the library, not by someone linking to an already compiled version to scratch their head over when/if it doesn't work in scenarios like you described. 

One would think that enumerating devices on any Linux distro would be rather consistent, so odd to see some experiencing this issue, while others do not. It would probably be outside the scope of GLFW, but perhaps it is hardware or kernel/driver related?

**Comment by iamAdrianIusca** [comment] 2020-03-01 21:02
If the solution with the window hint for disabling the joystick initialisation is ok for everyone, I can do a pull request.

**Comment by elmindreda** [comment] 2020-07-02 20:33
The best solution may be the SDL one: explicitly ask for subsystems as you need them. Something to consider for the next API revision.

For right now, I'm not at all opposed to an init hint for this.

Another option would be to delay joystick init until it is observable, that is until the application calls any joystick or gamepad function. We already delay init some things, for example context creation APIs and each monitor's video mode array.

**Comment by elmindreda** [comment] 2020-07-15 20:37
A quick test implementation of delay-initialized joysticks is now available in the `joystick-delay-init` branch. It's had a tiny bit of testing on all supported platforms.

Does this branch work for you?

**Comment by elmindreda** [comment] 2020-07-21 16:13
Delayed initialization of joystick support has been merged as 782e6b6cefc9ac2a2b6779f9e658ab948809253b.

**Comment by Luflosi** [comment] 2020-07-23 13:15
I think `_glfwDetectJoystickConnectionLinux()` is still being called, even when Joysticks are not being used. I'm not sure what this function actually does but can it also be disabled when no Joysticks are used?

**Comment by elmindreda** [comment] 2020-07-23 17:17
@Luflosi It is, though it should return immediately as the inotify fd will still be zero. Having a check before calling it would be clearer, though. Will fix.

It just checks for new devices in `/dev/input`. It works, though it should likely be replaced by calls to libudev.

**Comment by elmindreda** [comment] 2020-10-09 14:43
This issue should be addressed by the merged delayed init work. If not, please re-open or post an update.

**Closed by elmindreda** 2020-10-09 14:43 UTC
Labels: Linux, Windows, enhancement, input, macOS
