### ISSUE TITLE
Fail to create window on Sierra 10.12.6

### ISSUE THREAD

**Issue by jlyharia** [glfw/glfw#1057] opened 2017-08-05 18:39 UTC
Hi,
I've tried previous thread but still fail. (https://github.com/glfw/glfw/issues/909)

    glfwSetErrorCallback(error_callback);
    // GLFW
    if (!glfwInit())
        exit(EXIT_FAILURE);

    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 1);

    // init glfw windows
    GLFWwindow *window = glfwCreateWindow(300, 300, "Edit Academy 3D", nullptr, nullptr);

output
2017-08-05 11:31:38.358298-0700 clion[22364:1019537] [General] ERROR: Setting <GLFWContentView: 0x7f8a97f0c2d0> as the first responder for window <GLFWWindow: 0x7f8a97d0e0d0>, but it is in a different window ((null))! This would eventually crash when the view is freed. The first responder will be set to nil.

(
	0   AppKit                              0x00007fffd0e4b9cf -[NSWindow _validateFirstResponder:] + 557
	1   AppKit                              0x00007fffd05c674c -[NSWindow _setFirstResponder:] + 31
	2   AppKit                              0x00007fffd066e9ce -[NSWindow _realMakeFirstResponder:] + 406
	3   AppKit                              0x00007fffd066e7e4 -[NSWindow makeFirstResponder:] + 123
	4   libglfw.3.dylib                     0x000000010f938895 _glfwPlatformCreateWindow + 631
	5   libglfw.3.dylib                     0x000000010f934430 glfwCreateWindow + 487
	6   clion                               0x000000010f8b0e43 main + 147
	7   libdyld.dylib                       0x00007fffe823a235 start + 1
	8   ???                                 0x0000000000000001 0x0 + 1
)
OpenGL Version: 4.1 INTEL-10.25.17
GL_SHADING_LANGUAGE_VERSION: 4.10
GL_VENDOR: Intel Inc.
GL_RENDERER: Intel(R) Iris(TM) Graphics 6100

Process finished with exit code 0

GLFW homebrew info
glfw: stable 3.2.1 (bottled), HEAD
Multi-platform library for OpenGL applications

IDE:
Clion

I don't know if I need to try this method
https://stackoverflow.com/a/41160141

Please help me. Thanks

**Comment by elmindreda** [comment] 2017-08-05 22:25
When you are using the up-to-date version of GLFW you compiled yourself, what does `glfwGetVersionString` return?

**Comment by jlyharia** [comment] 2017-08-05 22:28
glfwGetVersionString: 3.2.1 Cocoa NSGL chdir menubar retina dynamic

**Comment by elmindreda** [comment] 2017-08-05 23:25
Then the problem is likely the same as in #909: you're not linking against the library you built. The version currently in `master`, that contains the fix for this issue, is 3.3.0.

**Comment by jlyharia** [comment] 2017-08-06 22:25
Thank you for your help.
I build from master with shared lib and it works

cmake -DBUILD_SHARED_LIBS=ON .

**Comment by elmindreda** [comment] 2017-08-06 22:29
Glad it worked and thank you for the follow-up!

**Closed by elmindreda** 2017-08-06 22:29 UTC
Labels: bug, duplicate, macOS
