### ISSUE TITLE
Full screen problems on 10.6

### ISSUE THREAD

**Issue by notnot** [glfw/glfw#448] opened 2015-02-23 00:39 UTC
GLFW 3.0.4 doesn't switch to fullscreen properly on OS X 10.6, and neither does GLFW 3.1 (i hoped that this update fixed that bug). 

GLFW 3.0.4: i see a fullscreen window, but it remains black. OpenGL gives no errors.
GLFW 3.1: i don't see a window at all. OpenGL gives no errors.

Please look into this. GLFW is switching to fullscreen just fine on my newer OS X machines and on linux.

**Comment by elmindreda** [comment] 2015-02-23 01:52
Do the examples work?

**Comment by elmindreda** [comment] 2015-02-23 02:07
Also, does GLFW emit any errors?

**Comment by notnot** [comment] 2015-02-23 09:59
nothing works as it should...

**Comment by notnot** [comment] 2015-02-25 10:44
It is possibly helpful to you to say that the fullscreen mode worked well on OS X 10.6 with the older GLFW 2 series.

**Comment by elmindreda** [comment] 2015-02-25 11:40
It is, but not sufficiently to know what the problem is. The full screen code was completely rewritten for 3.1.

**Comment by elmindreda** [comment] 2015-03-17 13:27
Does GLFW 3.0 work on 10.6?

**Comment by notnot** [comment] 2015-03-17 17:48
Yes it does, well i the parts that my applications use do indeed work on OS
X 10.6. I figure you don't have a machine at your disposal to test and
reproduce this bug?

**Comment by elmindreda** [comment] 2015-03-17 18:05
Yes, unfortunately.

**Comment by notnot** [comment] 2015-03-17 18:24
Once i find the time, i'll dive into the GLFW source and see if i can get
it to work well on a variety of OS X versions. I do have 10.6, 10.7, and
10.10 machines at my disposal. There are issues with mouse hiding as well
(OS X 10.7, maybe 10.6 too). As i said before, the GLFW 2 fullscreen code
worked well.

**Comment by shurcooL** [comment] 2015-05-01 04:18
Hi @notnot,

Is there a specific reason holding you back at Mac OS X 10.6 instead of upgrading to the latest OS X 10.10? OS X version 10.10 and all later updates are free, and include many under-the-hood as well as usability improvements. Is your Mac an older model that 10.10 does not support?

**Comment by notnot** [comment] 2015-05-01 08:15
I do have all kinds of OS X versions running myself, including the 'latest
and greatest', i do have a few machine that are too old to be updated to
10.10. My software is used by other people too, and should thus run on
whatever machines they have. It is more a question of principle: i want to
support a broad as possible range of machines. It is technically possible
to have perfect fullscreen behavior on OS X 10.6 (see GLFW 2), so why not
have it in GLFW 3...

**Comment by shurcooL** [comment] 2015-05-01 19:10
I see, that's a fair point. (Unfortunately I cannot assist with fixing an issue for a non-latest OS X version.)

**Comment by elmindreda** [comment] 2015-06-10 01:25
> It is technically possible to have perfect fullscreen behavior on OS X 10.6 (see GLFW 2), so why not have it in GLFW 3...

There is a limited amount of time available to work on GLFW and there are far more users running 10.7 or later than are running 10.6. As long as there are bugs that affect newer versions, those get priority. I'll gladly accept tested patches, however.

If this isn't resolved by the time 3.2 is done, I'll remove compatibility with 10.6 before release.

**Comment by notnot** [comment] 2015-06-10 17:16
Sad but understandable. It isn't important enough for me at the moment to
justify development time on it either...

**Comment by jaredjones** [comment] 2015-07-20 09:58
Also if this is added in its current form, 10.6 won't work as well... Unless you build on a newer SDK and target 10.6: 8d2bc5314f38f2cd636da1025f1e68137e6f165d is added to master

**Comment by elmindreda** [comment] 2015-07-20 11:19
@jaredjones Yep. I'll fix that before release if this gets resolved.

**Comment by AngeloYazar** [comment] 2015-10-19 01:05
Hey, I'm able to get the gears example to go fullscreen on OSX 10.6.8. Is that version too new? I had to change cocoa_window.m a bit to get it to compile, but no other changes were needed.

**Comment by notnot** [comment] 2015-10-19 09:45
Great! Will the changes you made be incorporated into glfw? If not, i'd
like to have a copy of your cocoa_window.m to patch my own old 10.6.8
laptop.

**Comment by elmindreda** [comment] 2015-10-19 13:11
@AngeloYazar It's the best version.

@notnot If the changes allow GLFW to function properly on 10.6 then absolutely!

**Comment by AngeloYazar** [comment] 2015-10-19 19:25
@notnot I'm not sure if it will fix the problem for you, since I really didn't fix anything. I just made sure it would compile by adding back in all the #if MAC_OS_X_VERSION_MAX_ALLOWED >= 1070 stuff and making a convertRectToBacking function. Try building with this file to see if it works for you: https://gist.github.com/AngeloYazar/1210af2206f8dbf63b51

Opening the examples to fullscreen worked just by adding glfwGetPrimaryMonitor() to glfwCreateWindow. Was that the original error? Or was there a different issue?

@elmindreda agreed!

**Comment by notnot** [comment] 2015-10-27 12:28
@angelo, i don't have access to a 10.6.8 machine at the moment, so i can't
try it.

**Comment by AngeloYazar** [comment] 2015-10-27 18:59
@notnot Do you have some example code that was failing? I can try to run it on my machine. Also, do you remember if it was related to switching between windowed and fullscreen?

**Comment by notnot** [comment] 2015-10-28 01:48
the example fullscreen code was failing: no window at all was opened. and
all my own programs failed (no window)

**Comment by AngeloYazar** [comment] 2015-10-28 06:08
Okay great, we just need someone to confirm that the code is working.

**Comment by elmindreda** [comment] 2016-02-28 19:25
Adding this to 3.2 so I won't forget to close it if it hasn't been resolved by then.

**Closed** 2016-03-31 11:58 UTC
Labels: bug, OS X, wontfix
